src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Extentor</fullName>
        <active>true</active>
        <label>Extentor</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_Joining__c</fullName>
        <label>Date of Joining</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Extentor</fullName>
        <active>true</active>
        <label>Extentor</label>
    </recordTypes>
</CustomObject>

src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{00000}</displayFormat>
        <label>Leave Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_Joining__c</fullName>
        <label>Date of Joining</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LM_LeaveRequestCalendarClass_TestClass.cls
@isTest(SeeAllData=true)
private class LM_LeaveRequestCalendarClass_TestClass{
    // private static account testaccount;
    //  private static contact testcontact;
    private static user testUser;
    private static Leave_Request__c testleave;
    
    private static void init()
   {
   User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs (thisUser)
        { 
        
            //String extentorAccountid = [Select id from userrole  where name='Developer'  limit 1].id;
            testUser=InitializeTestData.createUser('user5@testorg.com');
            //testUser.UserRoleId=extentorAccountid;
            testUser.Date_of_Joining__c=date.today();
            testUser.Total_Leave__c=21;
            Database.insert(testUser);
        }
         
          Date startDate=Date.newInstance(date.today().year(),07,03);
        Date endDate=Date.newInstance(date.today().year(),07,07);
        testleave=InitializeTestData.createLeaveRequest(testUser.id,startDate,endDate);
        database.insert(testleave);
       
       }
    
    
    private static Testmethod void RequestCalender(){
        init();
        
        LM_LeaveRequestCalendarClass_v3  leaveRequestCalendar=  new LM_LeaveRequestCalendarClass_v3 ();
        LM_LeaveRequestCalendarClass_v3.LeaveDetails_WrapperClass leavedetail=new LM_LeaveRequestCalendarClass_v3.LeaveDetails_WrapperClass();
        leaveRequestCalendar.selectedMonth = '7';
        leaveRequestCalendar.selectedYear = String.valueOf(date.today().year());
        leaveRequestCalendar.next();
        leaveRequestCalendar.getEmployeeLeaveDetails();
        //  List<Contact> allEmployees = [select id, name from Contact where Account.name='Extentor' and Exit_date__c = null ORDER BY name ASC];
        String employeeId = null;
        // List<Leave_Request__c> leaveRequestsForMonth = [ select Employee__c,Employee__r.Name,End_date__c,Start_Date__c,Status__c from Leave_Request__c where (CALENDAR_MONTH(Start_Date__c) = :Integer.valueOf(selectedMonth) OR CALENDAR_MONTH(End_Date__c) = :Integer.valueOf(selectedMonth)) AND CALENDAR_YEAR(Start_Date__c) = :Integer.valueOf(selectedYear) order by Employee__c,Start_Date__c];
        leaveRequestCalendar.getTotalMonths();
        leaveRequestCalendar.getTotalYears();
        leaveRequestCalendar.getMonthName();
        leaveRequestCalendar.next();
        leaveRequestCalendar.test();
   LM_LeaveRequestCalendarClass_v3.approveRecord(testleave.id,'testing');
LM_LeaveRequestCalendarClass_v3.rejectRecord(testleave.id,'testing');
    }
}