src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Invoice Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Item</label>
        <referenceTo>Sales_Order_Item__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILIN-{0000000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT(Sales_Order__r.Billing_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Percent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT( Sales_Order__r.Billing_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completely Invoiced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <label>Sales Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Tax Code</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PM_InvoiceController_FP_TestClass.cls
@isTest(seeAlldata=false)
private class PM_InvoiceController_FP_TestClass{
 static User testUser1;
    static User testUser2;
    static Customer__c testCompany;
    static Deal__c testDeal;
    static Resource_Forecast__c testResourceForecast1;
    static Allocation__c testAllocation1;
    static Allocation__c testAllocation2;
    static Sales_Order__c testSalesOrder;
    static Project__c testProject;
    static Sales_Order_Item__c testSalesOrderItem1;
    static Sales_Order_Item__c testSalesOrderItem2;
    static Invoice__c testInvoice;
    static Invoice_Line_Item__c testInvoiceLineItem1;
    static Invoice_Line_Item__c testInvoiceLineItem2;
    static Tax_Code__c testTaxCode;
    
    public static void init()    
    {
        
        
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        testUser1=InitializeTestData.createUser('user31@testorg.com');
        testUser1.EmployeeNumber = '1234234344';
        database.insert(testUser1);
        
        testUser2=InitializeTestData.createUser('user32@testorg.com');
        testUser2.LastName = 'Testing1';
        testUser2.Alias = 'standt1';
        testUser2.UserName = 'test12874@extentor.com';
        testUser2.EmployeeNumber = '1234234345';
        database.insert(testUser2);
        
        testCompany=InitializeTestData.createCustomer();
        testCompany.Name='ClientCompany';
        database.insert(testCompany);
        
        testDeal=InitializeTestData.createServiceDeal(testCompany.Id);
        database.insert(testDeal);
        
        testResourceForecast1=InitializeTestData.CreateResource_Forecast(testDeal.Id);
        testResourceForecast1.Quantity__c = 2;
        database.insert(testResourceForecast1);
        
        
        testSalesOrder=InitializeTestData.createServiceSalesOrder(testDeal.Id);
        testSalesOrder.Customer__c = testCompany.Id;
        testSalesOrder.Billing_Type__c='T&M';
        testSalesOrder.Tax_Code__c = 'ST;VAT';
        testSalesOrder.Tax_Percent__c = '10;12.6';
        database.insert(testSalesOrder);
        
        testProject=InitializeTestData.createProject(testSalesOrder.Id);
        database.insert(testProject);
        
        testAllocation1=InitializeTestData.createAllocation(testProject.Id,testUser1.Id);
        database.insert(testAllocation1);
        
        testAllocation2=InitializeTestData.createAllocation(testProject.Id,testUser2.Id);
        database.insert(testAllocation2);
        
        testSalesOrderItem1=InitializeTestData.createServiceSalesOrderItem(testSalesOrder.Id);
        testSalesOrderItem1.Quantity__c=10;
        testSalesOrderItem1.Unit_Rate__c=5000;
        testSalesOrderItem1.UserId__c = testUser1.Id;
        testSalesOrderItem1.Status__c = 'Partially Invoiced';
        database.insert(testSalesOrderItem1);
        
        testSalesOrderItem2=InitializeTestData.createServiceSalesOrderItem(testSalesOrder.Id);
        testSalesOrderItem2.Quantity__c=10;
        testSalesOrderItem2.Unit_Rate__c=5000;
        testSalesOrderItem2.UserId__c = testUser2.Id;
        testSalesOrderItem2.Status__c = 'Partially Invoiced';
        database.insert(testSalesOrderItem2);
        
        testTaxCode=InitializeTestData.createTaxCode();
        database.insert(testTaxCode);
        
        testInvoice=InitializeTestData.createInvoice();
        testInvoice.Tax_Percent__c='10;25';
        database.insert(testInvoice);
        
        testInvoiceLineItem1=InitializeTestData.createInvoiceLineItem(testInvoice.id);
        testInvoiceLineItem1.Unit_Rate__c=1200;
        testInvoiceLineItem1.Invoice_Quantity__c=2;
        database.insert(testInvoiceLineItem1);
        
        testInvoiceLineItem2=InitializeTestData.createInvoiceLineItem(testInvoice.id);
        testInvoiceLineItem1.Unit_Rate__c=1500;
        testInvoiceLineItem1.Invoice_Quantity__c=12;
        database.insert(testInvoiceLineItem2);
        
        
        }
        
         static testmethod void InvoiceCreation_FP()
    {
        init();
        list<Sales_Order_Item__c> testSalesOrderItem=new list<Sales_Order_Item__c>();
        testSalesOrderItem.add(testSalesOrderItem1);
        testSalesOrderItem.add(testSalesOrderItem2);
        
        List<Invoice_Line_Item__c> testInvoiceLineItem=new List<Invoice_Line_Item__c>();
        testInvoiceLineItem.add(testInvoiceLineItem1);
        testInvoiceLineItem.add(testInvoiceLineItem2);
        
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_InvoiceCreationPage_FP?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.standardSetController(testSalesOrderItem);
        sc.setSelected(testSalesOrderItem);
        PM_InvoiceCreationPageController_FP invoice_FP = new PM_InvoiceCreationPageController_FP(sc);
        invoice_FP.getItems();
        invoice_FP.getInvoiceDetails();
        invoice_FP.getAdditionalLineItems();
        invoice_FP.getNewInvoiceLineItems();
        invoice_FP.Remove();
        invoice_FP.AddToInvoice();
        invoice_FP.goToStep2();
        invoice_FP.goToStep3();
        invoice_FP.goFromStep2ToStep3();
        invoice_FP.listofnewinvoicelineItems=testInvoiceLineItem;
        //invoice_FP.Save();
        //invoice_FP.removeLink();
        }



}