src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Recoverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestcreateAllocationsForLead.cls
@isTest
private class TestcreateAllocationsForLead {

static testMethod void testSave() {
Project__c project = new Project__c(); 
Test.startTest();
insert project;
List<Allocation__c> all = [Select Id From Allocation__c];
System.assertEquals(1, all.size());
Test.stopTest();
}
}
/*@istest(seealldata=true)
public class testcreateAllocationsForLead {
static testmethod void createAllocationsForLead (){        
    Project__c newPro=new Project__c ();
   // newPro.Project_Lead__c=userinfo.getuserid();
    newPro.Actual_Start_Date__c=date.today();
    newPro.Actual_End_Date__c=date.today();
    newPro.Project_Type__c='internal';
    insert newPro;
    }
 }*/