src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Consolidated_Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT( Sales_Order__r.Billing_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Consolidated Time Sheets</relationshipLabel>
        <relationshipName>Consolidated_Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completely Invoiced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Consolidated Time Sheet</label>
    <nameField>
        <label>Consolidated Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidated Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Consolidated_Time_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consolidated Time Sheet</label>
        <referenceTo>Consolidated_Time_Sheet__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILIN-{0000000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT(Sales_Order__r.Billing_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Percent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Tax Code</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PM_InvoiceCreationController_TestClass.cls
@isTest(seeAlldata=false)
private class PM_InvoiceCreationController_TestClass
{
    static User testUser1;
    static User testUser2;
    static Customer__c testCompany;
    static Deal__c testDeal;
    static Resource_Forecast__c testResourceForecast1;
    static Allocation__c testAllocation1;
    static Allocation__c testAllocation2;
    static Sales_Order__c testSalesOrder;
    static Project__c testProject;
    static Consolidated_Time_Sheet__c testSalesOrderItem1;
    static Consolidated_Time_Sheet__c testSalesOrderItem2;
    static Invoice_Line_Item__c testInvoiceLineItem;
    
    public static void init()    
    {
        
        
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        testUser1=InitializeTestData.createUser('user16@testorg.com');
        testUser1.EmployeeNumber = '1234234344';
        database.insert(testUser1);
        
        testUser2=InitializeTestData.createUser('user20@testorg.com');
        testUser2.LastName = 'Testing1';
        testUser2.Alias = 'standt1';
        testUser2.UserName = 'test1234@extentor.com';
        testUser2.EmployeeNumber = '1234234345';
        database.insert(testUser2);
        
        testCompany=InitializeTestData.createCustomer();
        testCompany.Name='ClientCompany';
        database.insert(testCompany);
        
        testDeal=InitializeTestData.createServiceDeal(testCompany.Id);
        database.insert(testDeal);
        
        testResourceForecast1=InitializeTestData.CreateResource_Forecast(testDeal.Id);
        testResourceForecast1.Quantity__c = 2;
        database.insert(testResourceForecast1);
        
        
        testSalesOrder=InitializeTestData.createServiceSalesOrder(testDeal.Id);
        testSalesOrder.Customer__c = testCompany.Id;
        testSalesOrder.Billing_Type__c='T&M';
        testSalesOrder.Tax_Code__c = 'ST;VAT';
        testSalesOrder.Tax_Percent__c = '10;12.6';
        database.insert(testSalesOrder);
        
        testProject=InitializeTestData.createProject(testSalesOrder.Id);
        database.insert(testProject);
        
        testAllocation1=InitializeTestData.createAllocation(testProject.Id,testUser1.Id);
        database.insert(testAllocation1);
        
        testAllocation2=InitializeTestData.createAllocation(testProject.Id,testUser2.Id);
        database.insert(testAllocation2);
        
        testSalesOrderItem1=InitializeTestData.createServiceConsolidatedTimeSheet(testSalesOrder.Id);
        testSalesOrderItem1.Quantity__c=10;
        testSalesOrderItem1.Unit_Rate__c=5000;
        testSalesOrderItem1.UserId__c = testUser1.Id;
        testSalesOrderItem1.Status__c = 'Completed';
        database.insert(testSalesOrderItem1);
        
        testSalesOrderItem2=InitializeTestData.createServiceConsolidatedTimeSheet(testSalesOrder.Id);
        testSalesOrderItem2.Quantity__c=10;
        testSalesOrderItem2.Unit_Rate__c=5000;
        testSalesOrderItem2.UserId__c = testUser2.Id;
        testSalesOrderItem2.Status__c = 'Completed';
        database.insert(testSalesOrderItem2);
        
        
        
    }
    static testmethod void checkInvoiceCreation()
    {
        init();
        List<Consolidated_Time_Sheet__c> listofSalesOrderItem = new List<Consolidated_Time_Sheet__c>(); 
        listofSalesOrderItem.add(testSalesOrderItem1);
        listofSalesOrderItem.add(testSalesOrderItem2);
        Test.startTest();
        PageReference pg = new PageReference('/apex/InvoiceCreationPage?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listofSalesOrderItem);
        sc.setSelected(listofSalesOrderItem );
        PM_InvoiceCreationPageController controller=new PM_InvoiceCreationPageController(sc);
        controller.getItems();
        controller.goToStep2();
        controller.AddToInvoice();
        controller.getInvoiceDetails();
        controller.getNewInvoiceLineItems();
        controller.getAdditionalLineItems();
        controller.Save();
        Test.stopTest();
    }
    static testmethod void checkInvoiceCreation1()
    {
        init();
        List<Consolidated_Time_Sheet__c> listofSalesOrderItem = new List<Consolidated_Time_Sheet__c>(); 
        listofSalesOrderItem.add(testSalesOrderItem1);
        listofSalesOrderItem.add(testSalesOrderItem2);
        Test.startTest();
        PageReference pg = new PageReference('/apex/InvoiceCreationPage?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listofSalesOrderItem);
        sc.setSelected(listofSalesOrderItem );
        PM_InvoiceCreationPageController controller=new PM_InvoiceCreationPageController(sc);
        controller.valueToRemove = String.valueOf(testSalesOrderItem1.Id);
        controller.Remove();
        controller.getItems();
        controller.goToStep2();
        controller.AddToInvoice();
        controller.getInvoiceDetails();
        controller.getNewInvoiceLineItems();
        controller.getAdditionalLineItems();
        controller.Save();
        Test.stopTest();
    }
    static testmethod void checkInvoiceCreation2()
    {
        init();
        List<Consolidated_Time_Sheet__c> listofSalesOrderItem = new List<Consolidated_Time_Sheet__c>(); 
        listofSalesOrderItem.add(testSalesOrderItem1);
        listofSalesOrderItem.add(testSalesOrderItem2);
        Test.startTest();
        PageReference pg = new PageReference('/apex/InvoiceCreationPage?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listofSalesOrderItem);
        sc.setSelected(listofSalesOrderItem );
        PM_InvoiceCreationPageController controller=new PM_InvoiceCreationPageController(sc);
        controller.valueToRemove = String.valueOf(testSalesOrderItem1.Id);
        controller.Remove();
        controller.getListOfTaxCodeWrappers();
        controller.getItems();
        controller.goToStep2();
        controller.goToStep3();
        controller.goFromStep2ToStep3();
        controller.AddToInvoice();
        ApexPages.currentPage().getParameters().put('removeRow','1');
        controller.removeLink();
        controller.getInvoiceDetails();
        controller.getNewInvoiceLineItems();
        controller.getAdditionalLineItems();
        controller.Save();
        Test.stopTest();
    }
    static testmethod void checkInvoiceCreation3()
    {
        init();
        testSalesOrderItem1.Status__c = 'In-Progress';
        List<Consolidated_Time_Sheet__c> listofSalesOrderItem = new List<Consolidated_Time_Sheet__c>(); 
        listofSalesOrderItem.add(testSalesOrderItem1);
        listofSalesOrderItem.add(testSalesOrderItem2);
        Test.startTest();
        PageReference pg = new PageReference('/apex/InvoiceCreationPage?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listofSalesOrderItem);
        sc.setSelected(listofSalesOrderItem );
        PM_InvoiceCreationPageController controller=new PM_InvoiceCreationPageController(sc);
        controller.valueToRemove = String.valueOf(testSalesOrderItem1.Id);
        controller.Remove();
        controller.getListOfTaxCodeWrappers();
        controller.getItems();
        controller.goToStep2();
        controller.goToStep3();
        controller.goFromStep2ToStep3();
        controller.AddToInvoice();
        ApexPages.currentPage().getParameters().put('removeRow','1');
        controller.removeLink();
        controller.getInvoiceDetails();
        controller.getNewInvoiceLineItems();
        controller.getAdditionalLineItems();
        controller.Save();
        Test.stopTest();
    }
    static testmethod void checkInvoiceCreation4()
    {
        init();
        testCompany.CurrencyIsoCode = 'AUD';
        database.update(testCompany);
        List<Consolidated_Time_Sheet__c> listofSalesOrderItem = new List<Consolidated_Time_Sheet__c>(); 
        listofSalesOrderItem.add(testSalesOrderItem1);
        listofSalesOrderItem.add(testSalesOrderItem2);
        Test.startTest();
        PageReference pg = new PageReference('/apex/InvoiceCreationPage?rec='+testSalesOrderItem1.Id+';'+testSalesOrderItem2.Id+'&id='+testSalesOrder.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(listofSalesOrderItem);
        sc.setSelected(listofSalesOrderItem );
        PM_InvoiceCreationPageController controller=new PM_InvoiceCreationPageController(sc);
        controller.getItems();
        controller.goToStep2();
        controller.AddToInvoice();
        controller.getInvoiceDetails();
        controller.getNewInvoiceLineItems();
        controller.getAdditionalLineItems();
        controller.Save();
        Test.stopTest();
    }
}