src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN - Project Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability (%)</label>
        <picklist>
            <controllingField>Stage__c</controllingField>
            <picklistValues>
                <fullName>10%</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>20%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>75%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_End_Date__c</fullName>
        <label>Actual End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Proposed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectReportController.cls
public without sharing class ProjectReportController {

    public List<SelectOption> projectNameOption {get; set;}
    public List<Project__c> projectNameList {get; set;}
    public String projectProbability {get; set;}
    public String projectId {get; set;}
    
    public ProjectReportController(){ 
        string queryString = 'Select Name From Project__c Where Status__c = \'In-Progress\'';
        List<Project__c> projectName = Database.query(queryString);
        projectNameOption = new List<SelectOption>();
        projectNameOption.add(new SelectOption('NULL', ' -- Select -- '));
        for(Project__c P: projectName){
            projectNameOption.add(new SelectOption(P.Id, P.Name)); 
        }
    }
    
    public List<SelectOption> getDealProbability(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('NULL', ' -- Select -- '));
        list<Schema.PicklistEntry> values = Deal__c.Probability__c.getDescribe().getPickListValues();
        for (Schema.PicklistEntry a : values)
        { 
            options.add(new SelectOption(a.getValue(), a.getLabel())); 
        }
        return options;
    }   
    
    public List<ProjectManagementWrapper> ListOfProjects {get;set;}
    
    public pageReference displayProjectDetail(){
        string queryString = 'Select Name, Sales_Order__r.Deal__c, Actual_Start_Date__c, Actual_End_Date__c From Project__c Where Status__c = \'In-Progress\'';
        if(projectProbability != 'NULL'){
            queryString += ' AND Sales_Order__r.Deal__r.Probability__c = : projectProbability';
        }
        if(projectId != 'NULL'){
            queryString += ' AND Id = : projectId';
        }
        projectNameList = Database.query(queryString);
        
        List<Resource_Forecast__c> listOfResourceForecast = [select Deal__c, Role__c, Start_Date__c, End_Date__c, Quantity__c From Resource_Forecast__c];
        
        Map<Id, List<Resource_Forecast__c>> mapOfResourceForecast = new Map<Id, List<Resource_Forecast__c>>();
        ListOfProjects = new List<ProjectManagementWrapper>();
        for(Resource_Forecast__c RF: listOfResourceForecast){
            if(mapOfResourceForecast.get(RF.Deal__c) != NULL){
                mapOfResourceForecast.get(RF.Deal__c).add(RF);
            }else{
                mapOfResourceForecast.put(RF.Deal__c, new List<Resource_Forecast__c>{RF});
            }
        }
        Map<Id, List<Allocation__c>> mapOfAllocation = new Map<Id, List<Allocation__c>>();
        
        List<Allocation__c> listOfAllocation = [Select Name, Project__c, Role__c From Allocation__c];
        for(Allocation__c allot: listOfAllocation){
            if(mapOfAllocation.get(allot.Project__c) != NULL){
                mapOfAllocation.get(allot.Project__c).add(allot);
            }else{
                mapOfAllocation.put(allot.Project__c, new List<Allocation__c>{allot});
            }
        }
        
        for(Project__c p: projectNameList) {
            String projectName;
            Decimal projectManager;
            Decimal teamLead;
            Decimal seniorDeveloper;
            Decimal developer;
            Decimal allotedProjectManager;
            Decimal allotedTeamLead = 0;
            Decimal allotedSeniorDeveloper;
            Decimal allotedDeveloper;
            Date startDate;
            Date endDate;
            
           
            for(Allocation__c allot: mapOfAllocation.get(p.Id)){
                if(allot.Role__c != NULL){
                    if(allot.Role__c.toUpperCase().contains('MANAGER')){
                        allotedProjectManager += 1;
                    }
                    if(allot.Role__c.toUpperCase().contains('LEAD')){
                        allotedTeamLead += 1;
                    }
                    if(allot.Role__c.toUpperCase().contains('SENIOR')){
                        allotedSeniorDeveloper += 1;
                    }
                    if(allot.Role__c.toUpperCase().contains('DEVELOPER')){
                        allotedDeveloper += 1;
                    }
                }
            }
            
            for(Resource_Forecast__c RF1: mapOfResourceForecast.get(p.Sales_Order__r.Deal__c)){
                                
                if(RF1.Role__c.toUpperCase().contains('MANAGER')){
                    projectManager = RF1.Quantity__c;
                }
                if(RF1.Role__c.toUpperCase().contains('LEAD')){
                teamLead = RF1.Quantity__c;
                }
                if(RF1.Role__c.toUpperCase().contains('SENIOR')){
                seniorDeveloper = RF1.Quantity__c;
                }
                if(RF1.Role__c.toUpperCase().contains('DEVELOPER')){
                developer = RF1.Quantity__c;
                }                
            }
            projectName = p.Name;
            startDate = p.Actual_Start_Date__c;
            endDate = p.Actual_End_Date__c;
                
            ListOfProjects.add(new ProjectManagementWrapper(p.Id, p.Name, projectManager, teamLead, seniorDeveloper, developer, allotedProjectManager, allotedTeamLead, allotedSeniorDeveloper, allotedDeveloper, startDate, endDate));
        }
        
        return null;
    }
    
    public class ProjectManagementWrapper{
        public String projectId{get;set;}
        public String projectName{get;set;}
        public Decimal projectManager{get;set;}
        public Decimal teamLead{get;set;}
        public Decimal seniorDeveloper{get;set;}
        public Decimal developer{get;set;}
        public Decimal allotedProjectManager{get;set;}
        public Decimal allotedTeamLead{get;set;}
        public Decimal allotedSeniorDeveloper{get;set;}
        public Decimal allotedDeveloper{get;set;}
        public Date startDate{get;set;}
        public Date endDate{get;set;}
       
        public ProjectManagementWrapper(Id pId, String pName, Decimal pManager, Decimal tLead, Decimal sDeveloper, Decimal dev, Decimal aPManager, Decimal aTLead, Decimal aSDeveloper, Decimal aDev , Date sDate, Date eDate)
        {
            projectId = pId;
            projectName = pName;
            projectManager = pManager;
            teamLead = tLead;
            seniorDeveloper = sDeveloper;
            developer = dev; 
            allotedProjectManager = aPManager;
            allotedTeamLead = aTLead;
            allotedSeniorDeveloper = aSDeveloper;
            allotedDeveloper = aDev;            
            startDate = sDate; 
            endDate = eDate;

        }
    }
    
}