src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_Put_in_by_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Effort Put in by User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time worked in hours</description>
        <label>Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/TimeEntryPageMobileController.cls
global with sharing class TimeEntryPageMobileController {
    //Attributes
    public String userAgent {get;set;}
    public static final Integer DAY_DIFF = 5; 
    //Constructor
    public TimeEntryPageMobileController () {
        userAgent = ApexPages.currentPage().getHeaders().get('USER-AGENT');
        
        if(userAgent.contains('iPhone') || userAgent.contains('iPad') || userAgent.contains('iPod')){
        
            userAgent = 'iPhone';
        
        }else{
        
            userAgent = 'Others';
        }
        /*
        if(userAgent.contains('webOS') || userAgent.contains('iPhone') || userAgent.contains('iPad') || userAgent.contains('iPod') || userAgent.contains('BlackBerry') || userAgent.contains('Windows Phone') || userAgent.contains('Android')) {
            userAgent ='Phone';
        }
        else{
            userAgent ='Desktop';
        }
       */
    }
    
    //Methods
    /*
    Code for the page TimeEntryPageMobile
    */
    //Get projects 
    @RemoteAction
    global static List<Project__c> queryProjectsName() {
        return [select Id,Name from Project__c where Status__c = 'In-Progress'  AND Id IN(select Project__c from Allocation__c where Assigned_User__c=:UserInfo.getUserId())  order by Name];
    }

    //Get project tasks
    @RemoteAction
    global static List<Project_Task__c> queryProjectTasks(String ids) {
        return [Select Id,Name from Project_Task__c where Project__c=:ids];
    }
    
    //Bar Data Class
    
    global class BarChartClass{
    
        public String dateValue {get;set;}
        public Decimal effort {get;set;}
        
        public BarChartClass(String d,Decimal d1){
        
            this.dateValue = d;
            this.effort = d1;
            
        }
    
    
    }
    
    @RemoteAction
    global static List<BarChartClass> fetchLastFiveDayTimeEntry() {
        
        List<BarChartClass> barDataList = new List<BarChartClass>();
        
        Date fDate = Date.today().addDays(-1*DAY_DIFF);
        Date tDate = Date.today();
        
 
        
        Map<Integer,Decimal> effortPerDate = new Map<Integer,Decimal>();
        
        
        
    
        for(Time_Entry__c tEntry : [SELECT id,Effort__c,Date__c FROM Time_Entry__c WHERE Date__c >=:fDate AND Date__c <= :tDate AND Effort_Put_in_by_User__c =: UserInfo.getUserId() Order by Date__c]){
            
            
            if(effortPerDate.get(tEntry.Date__c.day()) == null){
            
                effortPerDate.put(tEntry.Date__c.day(),tEntry.Effort__c);
            
            }else{
            
                Decimal temp = effortPerDate.get(tEntry.Date__c.day());
                temp = temp + tEntry.Effort__c;
                effortPerDate.put(tEntry.Date__c.day(),temp);
            
            }

        
        }
        
        List<Integer> keyValues = new List<Integer>();
        Set<Integer> temp1 = new Set<Integer>();
        
        temp1 =  effortPerDate.keySet();
        keyValues.addAll(temp1);
        keyValues.sort();
        
        for(Integer keyV : keyValues){
        
                    
            BarChartClass b = new BarChartClass(String.valueOf(keyV),effortPerDate.get(keyV));
            barDataList.add(b);
        
        }
        
        return barDataList;
    }

    //Save time entry
    
    @RemoteAction
    
    global static String saveTimeEntryRecord(String projId,String taskId,String dt,String actDes,String eff,Boolean b) {
     
     system.debug(dt);
     String[] str = dt.split('-');
     Date d = date.newinstance(Integer.valueOf(str[0]), Integer.valueOf(str[1]), Integer.valueOf(str[2]));
     system.debug(projId + '' + taskId + '' + d + '' + actDes + '' + Decimal.valueof(eff) + '' + b);
     
     
     Time_Entry__c tEntry = new Time_Entry__c(Project__c = projId ,Related_Task__c =taskId ,Date__c = d,Activity_Description__c =actDes ,Effort__c = Decimal.valueof(eff),Client_Recoverable__c = b, Effort_Put_in_by_User__c = UserInfo.getUserId());
       
     try{
        system.debug(tEntry);
        insert tEntry;
     
     return 'Successfully Created';
     }catch(Exception e){
     
     return e.getMessage();
     }
     
    
    }
}