src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN - Project Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Consolidated_Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Consolidated Time Sheets</relationshipLabel>
        <relationshipName>Consolidated_Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completely Invoiced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Consolidated Time Sheet</label>
    <nameField>
        <label>Consolidated Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidated Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Category__c</fullName>
        <label>Project Category</label>
        <picklist>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement      </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <label>Project Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Category__c</fullName>
        <label>Project Category</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completely Invoiced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <label>Sales Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assessing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recovering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PM_Consolidated_time_sheet_TestClass.cls
@isTest(SeeAllData=false)
private class  PM_Consolidated_time_sheet_TestClass
{
    private static Customer__c NewCustomer;
    private static Deal__c NewDeal;
    private static Sales_Order__c newSalesOrder;
    private static Sales_Order_Item__c newsalesorderitems;
    private static Project__c newProject; 
    private static Allocation__c newAllocation; 
    private static Resource_Forecast__c newresourceforecast;
    private static Consolidated_Time_Sheet__c newConsolidatedTimeSheet;
    private static user newuser; 
    private static Ticket__c newticket; 
    private static LM_CustomSetting__c  newCustomsetting;
    //@future     
    private static void init()
    {
        
        //Test.startTest();
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        
        System.RunAs(usr)
        {
            
            newuser= InitializeTestData.createPLUser();
            database.insert(newuser);
            
        }
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createServiceDeal(NewCustomer.id);
        database.insert(NewDeal);
        newresourceforecast=InitializeTestData.CreateResource_Forecast(NewDeal.id);
        database.insert(newresourceforecast);
        newSalesOrder=InitializeTestData.createServiceSalesOrderTM(NewDeal.id);
        newSalesOrder.Status__c='Open';
        newSalesOrder.Project_Category__c='Maintenance';
        database.insert(newSalesOrder);
        newProject=  InitializeTestData.createProject(newSalesOrder.id);
        newProject.Project_Code__c='X-00-11-@231-&125';
        newProject.Project_Category__c='Maintenance';
        database.insert(newProject);
        
        newAllocation =InitializeTestData.createAllocation(newProject.id,newuser.id);
        //newAllocation.Role__c='Developer';
        database.insert(newAllocation );
        newticket =InitializeTestData.createTicket();
        newticket.Assigned_User__c=newuser.id;
        newticket.Project__c =newProject.id;
        database.insert(newticket);
        
        
        newsalesorderitems =InitializeTestData.createServiceSalesOrderItem(newSalesOrder.id);
        newsalesorderitems.UserId__c=newuser.id;
        database.insert(newsalesorderitems);
        newConsolidatedTimeSheet=InitializeTestData.createServiceConsolidatedTimeSheet(newSalesOrder.id);
        newConsolidatedTimeSheet.UserId__c=newuser.id;
        database.insert(newConsolidatedTimeSheet);
        //Test.stopTest();
        
        
    }
    
    // @future 
    
    private static void init2()
        
    {
        //Test.startTest();
        
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        
        System.RunAs(usr)
        {
            
            newuser= InitializeTestData.createUser('user12@testorg.com');
            
            database.insert(newuser);
        }
        
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createServiceDeal(NewCustomer.id);
        database.insert(NewDeal);
        newresourceforecast=InitializeTestData.CreateResource_Forecast(NewDeal.id);
        database.insert(newresourceforecast);
        newSalesOrder=InitializeTestData.createServiceSalesOrderTM(NewDeal.id);
        newSalesOrder.Status__c='Open';
        newSalesOrder.Project_Category__c='CB-LAUNCHPAD';
        database.insert(newSalesOrder);
        newProject=  InitializeTestData.createProject(newSalesOrder.id);
        newProject.Project_Category__c='CB-LAUNCHPAD';
        database.insert(newProject);
        
        newAllocation =InitializeTestData.createAllocation(newProject.id,newuser.id);
        //newAllocation.Role__c='Developer';
        database.insert(newAllocation );
        newsalesorderitems =InitializeTestData.createServiceSalesOrderItem(newSalesOrder.id);
        newsalesorderitems.UserId__c=newuser.id;
        database.insert(newsalesorderitems);
        newConsolidatedTimeSheet=InitializeTestData.createServiceConsolidatedTimeSheet(newSalesOrder.id);
        newConsolidatedTimeSheet.UserId__c=newuser.id;
        database.insert(newConsolidatedTimeSheet);
        //Test.stopTest();
        
        
        
    }
    
    
    
    //@future 
    private static void init3()
    {
        //Test.startTest();
        
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        
        System.RunAs(usr)
        {
            newuser= InitializeTestData.createPLUser();
            newuser.UserName='test1234567@extentor.com';
            database.insert(newuser);
            
        }
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createServiceDeal(NewCustomer.id);
        database.insert(NewDeal);
        newresourceforecast=InitializeTestData.CreateResource_Forecast(NewDeal.id);
        database.insert(newresourceforecast);
        newSalesOrder=InitializeTestData.createServiceSalesOrderTM(NewDeal.id);
        newSalesOrder.Status__c='Closed - Invoiced';
        newSalesOrder.Project_Category__c='CB-LAUNCHPAD';
        newSalesOrder.Billing_Type__c='FP';
        database.insert(newSalesOrder);
        newProject=  InitializeTestData.createProject(newSalesOrder.id);
        newProject.Project_Code__c='X-00-11-@231-&125456';
        newProject.Project_Category__c='CB-LAUNCHPAD';
        database.insert(newProject);
        User usr1 = [Select id from User where Id = :UserInfo.getUserId()];
        
        System.RunAs(usr1)
        {
            newuser= InitializeTestData.createPLUser();
            newuser.UserName='test123456789@extentor.com';
            database.insert(newuser);
        }
        newAllocation =InitializeTestData.createAllocation(newProject.id,newuser.id);
        //newAllocation.Role__c='Developer';
        database.insert(newAllocation );
        newticket =InitializeTestData.createTicket();
        newticket.Assigned_User__c=newuser.id;
        newticket.Project__c =newProject.id;
        database.insert(newticket);
        
        
        newsalesorderitems =InitializeTestData.createServiceSalesOrderItem(newSalesOrder.id);
        newsalesorderitems.UserId__c=newuser.id;
        database.insert(newsalesorderitems);
        newConsolidatedTimeSheet=InitializeTestData.createServiceConsolidatedTimeSheet(newSalesOrder.id);
        newConsolidatedTimeSheet.UserId__c=newuser.id;
        database.insert(newConsolidatedTimeSheet);
        //Test.stopTest();
        
        
    }
    
    // @future 
    private static void init4()
    {
        
        // Test.startTest();
        
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
        
        System.RunAs(usr)
        {
            newuser= InitializeTestData.createPLUser();
            newuser.UserName='test12345678@extentor.com';
            database.insert(newuser);     
        }
        
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createServiceDeal(NewCustomer.id);
        database.insert(NewDeal);
        newresourceforecast=InitializeTestData.CreateResource_Forecast(NewDeal.id);
        database.insert(newresourceforecast);
        newSalesOrder=InitializeTestData.createServiceSalesOrderTM(NewDeal.id);
        newSalesOrder.Status__c='Closed - Invoiced';
        newSalesOrder.Project_Category__c='Maintenance';
        newSalesOrder.Billing_Type__c='T&M';
        database.insert(newSalesOrder);
        newProject=  InitializeTestData.createProject(newSalesOrder.id);
        newProject.Project_Code__c='X-00-11-@231-&125456';
        newProject.Project_Category__c='Maintenance';
        database.insert(newProject);
        
        newAllocation =InitializeTestData.createAllocation(newProject.id,newuser.id);
        //newAllocation.Role__c='Developer';
        database.insert(newAllocation );
        newticket =InitializeTestData.createTicket();
        newticket.Assigned_User__c=newuser.id;
        newticket.Project__c =newProject.id;
        database.insert(newticket);
        
        
        newsalesorderitems =InitializeTestData.createServiceSalesOrderItem(newSalesOrder.id);
        newsalesorderitems.UserId__c=newuser.id;
        database.insert(newsalesorderitems);
        newConsolidatedTimeSheet=InitializeTestData.createServiceConsolidatedTimeSheet(newSalesOrder.id);
        newConsolidatedTimeSheet.UserId__c=newuser.id;
        database.insert(newConsolidatedTimeSheet);
        //Test.stopTest();
        
    }
    
    
    
    
    private static Testmethod void SalesorderitemStatusupdate()
    {
        
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        init();
        init2();
        init3();
        
        newSalesOrder.Status__c='Closed - Invoiced';
        update newSalesOrder ;
        
    }
    
    private static Testmethod void SalesorderitemStatusupdate2()
    {
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        init4();
        
        
        newSalesOrder.Status__c='Closed - Invoiced';
        update newSalesOrder ;
        
    }
    
    
    
    
    
}