src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Invoice Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Item</label>
        <referenceTo>Sales_Order_Item__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILIN-{0000000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT(Sales_Order__r.Billing_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Percent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT( Sales_Order__r.Billing_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <label>Sales Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Tax Code</label>
</CustomObject>

src/classes/PM_InvoicePDFGeneration_TestClass.cls
@isTest(seeAlldata = true)
private class PM_InvoicePDFGeneration_TestClass
{
    static User testUser;
    static Customer__c testCompany;
    static Deal__c testDeal;
    static Resource_Forecast__c testResourceForecast;
    static Allocation__c testAllocation;
    static Sales_Order__c testSalesOrder;
    static Project__c testProject;
    static Sales_Order_Item__c testSalesOrderItem;
    static Invoice__c testInvoice;
    static Invoice_Line_Item__c testInvoiceLineItem;
    public static void init()    
    {
        
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        testUser=InitializeTestData.createUser('user17@testorg.com');
        testUser.EmployeeNumber = '1234234344';
        database.insert(testUser);
        testCompany=InitializeTestData.createCustomer();
        testCompany.Name='ClientCompany';
        database.insert(testCompany);
        testDeal=InitializeTestData.createServiceDeal(testCompany.Id);
        database.insert(testDeal);
        testResourceForecast=InitializeTestData.CreateResource_Forecast(testDeal.Id);
        database.insert(testResourceForecast);
        testSalesOrder=InitializeTestData.createServiceSalesOrder(testDeal.Id);
        testSalesOrder.Customer__c = testCompany.Id;
        testSalesOrder.Billing_Type__c='T&M';
        
        database.insert(testSalesOrder);
        testProject=InitializeTestData.createProject(testSalesOrder.Id);
        database.insert(testProject);
        testAllocation=InitializeTestData.createAllocation(testProject.Id,testUser.Id);
        database.insert(testAllocation);
        testSalesOrderItem=InitializeTestData.createServiceSalesOrderItem(testSalesOrder.Id);
        testSalesOrderItem.Quantity__c=10;
        testSalesOrderItem.Unit_Rate__c=5000;
        testSalesOrderItem.UserId__c = ''+testUser.Id;
        database.insert(testSalesOrderItem);
        
        testInvoice=InitializeTestData.createInvoice();
        testInvoice.Tax_Percent__c = '12;43';
        testInvoice.Tax_Code__c = 'ST;VAT';
        database.insert(testInvoice);
        testInvoiceLineItem=InitializeTestData.createInvoiceLineItem(testInvoice.Id);
        testInvoiceLineItem.Invoice_Quantity__c=testSalesOrderItem.Quantity__c;
        testInvoiceLineItem.Unit_Rate__c=testSalesOrderItem.Unit_Rate__c;
        database.insert(testInvoiceLineItem);
    }
    static testmethod void checkInvoicePDF()
    {
        init();
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_PDFGenerationPage?id='+testInvoice.Id);
        Test.setCurrentPageReference(pg);
        ApexPages.StandardController sc = new ApexPages.standardController(testInvoice);
        PM_InvPDFGenerationPageController controller = new PM_InvPDFGenerationPageController(sc);
        controller.getInvoiceLineItem();
        controller.getTaxCode();
        Test.stopTest();
    }
}