src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_Put_in_by_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Effort Put in by User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time worked in hours</description>
        <label>Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeEntryController_v_1.cls
public class TimeEntryController_v_1 
{
    //public String currentUserId{get;set;}
    
    public String projectIdValue{get;set;}
    public String taskIdValue {get;set;}
    public String effortValue{get;set;}
    public String dateValue{get;set;}
    public String activityDescription{get;set;}
    public Boolean clientrecoverable{get;set;}
    public String timeEntryTab{get;set;}
    public String WeeklyViewTab{get;set;}
    public String BasicWizardTab{get;set;}
    public String Home{get;set;}
    public TimeEntryController_v_1()
    {
        timeEntryTab='active';
        WeeklyViewTab='#';
        BasicWizardTab='#';
        Home='#';
        //currentUserId = UserInfo.getUserId();
        //listOfProject = [select Id,Name from Project__c where Status__c = 'In-Progress'  AND Id IN(select Project__c from Allocation__c where Assigned_User__c=:UserInfo.getUserId())  order by CreatedDate];
    }
    public class taskProjectWrapper
    {
        public Integer counter{get;set;}
        public String projectId{get;set;}
        public List<Project_Task__c> projTaskList{get;set;}
    }
    public List<taskProjectWrapper> getUserProj()
    {
        try
        {
            List<Project__c> listOfProject = [select Id,Name from Project__c where Status__c = 'In-Progress'  AND Id IN(select Project__c from Allocation__c where Assigned_User__c=:UserInfo.getUserId())  order by Name];
            if(listOfProject!=null)
            {
                String projId = '';
                List<Project_Task__c> listProjTask;
                List<taskProjectWrapper> listtaskProj = new List<taskProjectWrapper>();
                //listtaskProject.
                //taskProjectWrapper instance;
                if(listOfProject!=null)
                {
                    for(Project_Task__c projTask:[select Id,Name,Project__c,Project__r.Name,Project__r.Id from Project_Task__c where Project__c IN:listOfProject order by Project__r.Name])
                    {
                        if(projId==''||projId!=projTask.Project__r.Name)
                        {
                            if(projId!='')
                            {
                                //System.debug('This is it '+projId);
                                taskProjectWrapper instance = new taskProjectWrapper();
                                instance.projTaskList = new List<Project_task__c>();
                                instance.projectId = String.valueOf(projId);
                                instance.projTaskList.addAll(listProjTask);
                                listtaskProj.add(instance);
                            }
                            projId = projTask.Project__r.Name;
                            listProjTask = new List<Project_Task__c>();
                            listProjTask.add(projTask);
                        }
                        else
                        {
                            listProjTask.add(projTask);
                        }
                    }
                    taskProjectWrapper instance = new taskProjectWrapper();
                    instance.projTaskList = new List<Project_task__c>();
                    instance.projectId = String.valueOf(projId);
                    instance.projTaskList.addAll(listProjTask);
                    listtaskProj.add(instance);
                    
                }
                for(integer i=0;i<listtaskProj.size();i++)
                {
                    listtaskProj[i].counter= i+1;
                }
                //System.debug(listtaskProj);
                return listtaskProj;
            }
            else
            {
                return null;
            }
        }
        catch(Exception e){return null;}
    } 
    public PageReference saveTimeEntryRecord()
    {
    
    System.debug('Project-> '+projectIdValue+' RelatedTask-> '+taskIdValue+' Effort-> '+effortValue+' ClientRecoverable-> '+clientrecoverable+' ActivityDescription-> '+activityDescription+' Date-> '+dateValue);
    Time_Entry__c newTimeEntry = new Time_Entry__c();
    newTimeEntry.Project__c = projectIdValue;
    newTimeEntry.Related_Task__c = taskIdValue ;
    newTimeEntry.Effort__c = Decimal.valueOf(effortValue);
    newTimeEntry.Effort_Put_In_by_User__c = UserInfo.getUserId();
    newTimeEntry.Date__c = date.parse(dateValue);
    newTimeEntry.Activity_Description__c = activityDescription;
    newTimeEntry.Client_Recoverable__c= Boolean.valueOf(clientrecoverable);
    newTimeEntry.Status__c = 'Saved';
    database.insert(newTimeEntry);
    
    //projectIdValue
    //taskIdValue
    //effortValue
    //dateValue    
    //activityDescription
    //clientrecoverable
    return null;
    }
    
    
    
}