src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LOP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_LOP__c</fullName>
        <label>Number of Days(LOP)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Optional_Holiday_Count__c</fullName>
        <label>Optional Holiday Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Optional_Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional Holiday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Working_days__c</fullName>
        <label>No. Leaves Applied</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{00000}</displayFormat>
        <label>Leave Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Optional_Holiday_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Optional Holiday Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <label>Reports to Manager</label>
        <relationshipName>ProjectLead1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LeaveRequestTriggerHandler.cls
public with sharing class LeaveRequestTriggerHandler{

//-- SINGLETON PATTERN
    private static LeaveRequestTriggerHandler instance;
    public static LeaveRequestTriggerHandler getInstance(){
        if (instance == null) instance = new LeaveRequestTriggerHandler();
          return instance;      
    }
    
    // -- ATTRIBUTES 
     Decimal leaveCount;
    List<Id> liftOfEmployeeIDs = new List<Id>();
    List<Id> projectList = new  List<Id>();
    List<Id> projectLeads = new List<Id>();
    Map<Id,User> userId_User_Map = new Map<Id,User>();
    List<User> listOfUsersToUpdate = new List<User>();
    String[] toAddresses = new String[10]; 
    
    //--CONSTANTS
    public static final Integer OPTIONAL_HOLIDAY_PERMITTED = 2;
   
    
     //-- METHODS 
     
    
    //-- After Insert
    
     public void onAfterInsert(final List<Leave_Request__c> newObjects,final Map<Id, Leave_Request__c> newObjectsMap){
     
     for(Leave_Request__c leaveReq : newObjects)
    {       
        liftOfEmployeeIDs.add(leaveReq.Employee__c);
    }
    
    for(User user: [select Id,Name,Total_Leave__c ,Optional_Holiday_Count__c from User where ID in :liftOfEmployeeIDs ]){
        userId_User_Map.put(user.Id,user);
    }
    
    for(Leave_Request__c leaveRequest : newObjects)
    {
            if(leaveRequest.Status__c=='Applied' && leaveRequest.Optional_Holiday__c==false)
            {
                User leaveUser = userId_User_Map.get(leaveRequest.Employee__c);
                if(leaveUser != null)
                {
                    leaveUser.Total_Leave__c= leaveUser.Total_Leave__c-leaveRequest.Total_Working_days__c;
                    if(leaveUser.Total_Leave__c < 0){
                        leaveUser.Total_Leave__c = 0;
                    }
                    listOfUsersToUpdate.add(leaveUser);
                    leaveCount = leaveRequest.Total_Working_days__c;
                }
                
               SendMailToLeads(leaveUser,leaveRequest);  
            }
           /*else if(lm.Status__c=='Cancelled' && lm.Optional_Holiday__c==false)
            {
                User u = userId_User_Map.get(lm.Employee__c);
                if(u != null)
                {
                    u.Total_Leave__c= u.Total_Leave__c+lm.Total_Working_days__c;
                    
                    listOfUsersToUpdate.add(u);
                    
                    
                }
                
                
                
                
            }*/
            
            else if(leaveRequest.Status__c=='Applied' && leaveRequest.Optional_Holiday__c==true)
            {
                User leaveUser = userId_User_Map.get(leaveRequest.Employee__c);
                if(leaveUser.Optional_Holiday_Count__c<=OPTIONAL_HOLIDAY_PERMITTED)
                {
                    
                    leaveUser.Optional_Holiday_Count__c =leaveUser.Optional_Holiday_Count__c+1;
                    
                    update leaveUser;
                }
                else
                    
                {
                    leaveRequest.addError('Employee cannot apply for more than two optional holidays');
                    
                }
               SendMailToLeads(leaveUser,leaveRequest);   
                
            }
     }
}
//--After Update
      
     public void onAfterUpdate(final List<Leave_Request__c> newObjects,final List<Leave_Request__c> oldObjects,final Map<Id, Leave_Request__c> newObjectsMap,final Map<Id, Leave_Request__c> oldObjectsMap){
     for(Leave_Request__c lm : newObjects)
    {
      if(lm.Status__c=='Applied' && lm.Optional_Holiday__c==false)
            {
                User u = userId_User_Map.get(lm.Employee__c);
                
                
                if(oldObjectsMap.get(lm.id).Start_Date__c != lm.Start_Date__c || oldObjectsMap.get(lm.id).End_Date__c != lm.End_Date__c )
                {
                    u.Total_Leave__c = u.Total_Leave__c+oldObjectsMap.get(lm.id).Total_Working_days__c;
                    System.debug('----------------------------------------'+u.Total_Leave__c);
                    //  u.Total_Leave__c =u.Total_Leave__c+leaveCount;
                    u.Total_Leave__c= u.Total_Leave__c-lm.Total_Working_days__c;
                    if(u.Total_Leave__c < 0){
                        u.Total_Leave__c = 0;
                    }
                    listOfUsersToUpdate.add(u);                  
                }
            }
            
            else if(lm.Status__c=='Cancelled' && lm.Optional_Holiday__c==false)          
            {
                User u = userId_User_Map.get(lm.Employee__c);               
                //if(trigger.oldMap.get(lm.id).Start_Date__c != lm.Start_Date__c || trigger.oldMap.get(lm.id).End_Date__c != lm.End_Date__c )
                if(oldObjectsMap.get(lm.id).Status__c!=lm.Status__c)
                {
                    if(lm.LOP__c){
                        u.Total_Leave__c= u.Total_Leave__c+lm.Total_Working_days__c - lm.Number_of_Days_LOP__c;
                    }
                    else{
                        u.Total_Leave__c= u.Total_Leave__c+lm.Total_Working_days__c;
                    }
                    listOfUsersToUpdate.add(u);                   
                }               
             }

        }
       }
            //--Sending Mail to Leads
            public void SendMailToLeads(User leaveUser,Leave_Request__c leaveRequest){
                 //User allocated projects
                 for(Allocation__c allocation :[SELECT Id,Project__c,Assigned_User__c FROM Allocation__c WHERE Assigned_User__c =: leaveUser.Id]){
                    projectList.add(allocation.Project__c);
                 }
                  //Sending mail to Project leads of the user
                 for(Project__c project : [SELECT id,Project_Lead__c,Project__c.Project_Lead__r.Email FROM Project__c WHERE id IN: projectList AND Status__c='In-Progress']){
                    projectLeads.add(project.Project_Lead__c); 
                    toAddresses.clear(); 
                    toAddresses.add(project.Project_Lead__r.Email);                 
                 }
                  
                  if(projectLeads.isEmpty()){
                  
                  }
                 System.assertEquals(toAddresses,null);
                if((!toAddresses.isEmpty())&&toAddresses!= null){                  
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();          
                mail.setToAddresses(toAddresses); 
                mail.setSubject('Team Member On Leave'); 
                String body = 'Dear, \r\n'+'\r\n'+ leaveUser.Name + ' has applied for leave from '+leaveRequest.Start_Date__c+' to '+leaveRequest.End_Date__c; 
                mail.setPlainTextBody(body); 
                Messaging.sendEmail(new Messaging.SingleEMailMessage[]{mail}); 
                }                                  
                }
}