src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT(Sales_Order__r.Billing_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/TimeEntryDetail_TestClass.cls
@isTest(seeAllData=true)
public class TimeEntryDetail_TestClass{
    static User testUser;
    static Customer__c testCompany1;
    static Deal__c testDeal1;
    static Allocation__c testAllocation1;
    static Sales_Order__c testSalesOrder1;
    static Project__c testProject1;
    static Project_Task__c testProjectTask1;
    static Allocation__c testAllocation2;
    static Time_Entry__c timeEntry1;
    static LM_CustomSetting__c customSetting;
    static Set<User> userId = new Set<User>();
    static User timeUser;
         
    static void init(){
        customSetting = InitializeTestData.LeaveAllocation();
        Database.insert(customSetting);
        for(integer i=0;i<10;i++){
            //users
        testUser=InitializeTestData.createUser('user25@testorg.com'+i);
        testUser.EmployeeNumber = '1234234344';
        Profile p = [SELECT Id FROM Profile WHERE Name='Developer Force One App']; 
        testUser.ProfileId = p.Id;
        testUser.Email = 'extentor.admn@extentor.com';
        Database.insert(testUser);
        userId.add(testUser) ;
        }
        //Company
         testCompany1=InitializeTestData.createCustomer();
        testCompany1.Name='ClientCompany';
        Database.insert(testCompany1);
        
        //ServiceDeal
        testDeal1=InitializeTestData.createServiceDeal(testCompany1.Id);
        Database.insert(testDeal1);
        
        //SalesOrder        
        testSalesOrder1=InitializeTestData.createServiceSalesOrderTM(testDeal1.Id);
        testSalesOrder1.Customer__c = testCompany1.Id;
        testSalesOrder1.Billing_Type__c='T&M';
        Database.insert(testSalesOrder1);
        
        //Project
        testProject1=InitializeTestData.createProject(testSalesOrder1.Id);      
        testProject1.Status__c = 'In-Progress';       
        Database.insert(testProject1);
        System.debug('#####'+testProject1);
        testProjectTask1=InitializeTestData.createProjectTask(testProject1.Id);
        testProjectTask1.Name = 'TestTask1';
        Database.insert(testProjectTask1);
        
        testAllocation1=InitializeTestData.createAllocation(testProject1.Id,testUser.Id);
        Database.insert(testAllocation1);
        
        for(User timeUsers : userId){
        Integer i = 1;
        if(math.mod(i,2)==0){
        timeEntry1 = InitializeTestData.createRWTimeEntry(timeUsers.Id , testProject1.Id, testProjectTask1.Id);
        timeEntry1.Date__c = System.today();
        timeEntry1.Client_Recoverable__c = true ;
        Database.insert(timeEntry1); 
        System.debug('####'+timeEntry1);
        }else{
        timeEntry1 = InitializeTestData.createRWTimeEntry(timeUsers.Id , testProject1.Id, testProjectTask1.Id);
        timeEntry1.Date__c = System.today();
        timeEntry1.Client_Recoverable__c = false ;
        Database.insert(timeEntry1);
        System.debug('####'+timeEntry1);
        System.debug('#####'+timeEntry1.Project__r.Name);
        testProject1.Name = 'Extentor-Product'  ;
        update testProject1;
        System.debug('#####Later'+testProject1.Name);
        }   
        i = i + 1;   
        }
  }  
     static testMethod void TimeEntriesDetails(){   
            TimeEntryDetail timeEntry = new TimeEntryDetail();
            timeEntry.StartDate = '06/04/2014';
            timeEntry.EndDate = System.today().format();                    
            init();
            Test.startTest();
            TimeEntryDetail.getPiaDataForJavaScript('01/03/14',system.today().format());
            TimeEntryDetail.getGrahicalDateForBarChart('01/03/14',system.today().format());
            TimeEntryDetail.getIndividualPieChart(testUser.Id,'01/03/14',system.today().format());
            timeEntry.search();
            timeEntry.details();
            timeEntry.graphicalView();
            timeEntry.tableView();
            timeEntry.getSelectList();
            timeEntry.getPieData();
            timeEntry.getBarDataClass();
            timeEntry.getDataTableClass();
            TimeEntryDetail.getUserNames();
            TimeEntryDetail.graphicalViewJS();
            timeEntry1.Client_Recoverable__c= true;
            update timeEntry1;
            TimeEntryDetail.getIndividualPieChart(testUser.Id,'01/03/14',system.today().format());
            Test.stopTest();
     }

     static testMethod void TimeEntriesDetailsForAll(){   
            TimeEntryDetail timeEntry = new TimeEntryDetail();
            timeEntry.StartDate = '06/04/2014';
            timeEntry.EndDate = System.today().format();                    
            init();
            Test.startTest();
            timeEntry.SelectedOption = 'Vivek Deepak';
            TimeEntryDetail.getPiaDataForJavaScript('01/03/14',system.today().format());
            TimeEntryDetail.getGrahicalDateForBarChart('01/03/14',system.today().format());
            TimeEntryDetail.getIndividualPieChart(testUser.Id,'01/03/14',system.today().format());
           
            timeEntry.search();
            timeEntry.details();
            timeEntry.graphicalView();
            timeEntry.tableView();
            timeEntry.getSelectList();
            timeEntry.getPieData();
            timeEntry.getBarDataClass();
            timeEntry.getDataTableClass();
            TimeEntryDetail.getUserNames();
            TimeEntryDetail.graphicalViewJS();
            timeEntry1.Client_Recoverable__c= true;
            update timeEntry1;
            TimeEntryDetail.getIndividualPieChart(testUser.Id,'01/03/14',system.today().format());
            Test.stopTest();
     }
    static testMethod void TimeEntriesDetails_V2(){ 
        TimeEntryDetail.DataTableClass td = new TimeEntryDetail.DataTableClass('test Name','test Proj', 8, 'test desc');
        //TimeEntryDetail.getIndividualPieChart('123456','01/03/14',system.today().format());
    }
}