src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offsite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN - Project Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Allocation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Proposed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Services</label>
</CustomObject>

src/classes/PM_ProjectAllocation.cls
global class PM_ProjectAllocation {
    
    /* To create project allocation records 

Author: Ashwin 

Created Date :

Last Modified Date :25/09/2013

Reason: To fetch roles from the custom setting 


*/
    public Boolean refreshPage{get;set;}
    public Boolean WholePage{get;set;}
    public String selectedValue{get;set;}
    Public Allocation__c ProjectAllocation; 
    Public List<Allocation__c> fetchAllocation {get;set;}
    public String selectedRole{get;set;}
    
    //To get allocated roles from the resource forecast 
    public List<SelectOption> getAvailableRoles()
    {
        List<SelectOption> options = new List<SelectOption>();
       /* for(Resource_Forecast__c dealItem: [select Role__c from Resource_Forecast__c where Deal__c = :selectedProject .Sales_Order__r.Deal__c])
        {
            options.add( new SelectOption(dealItem.Role__c, dealItem.Role__c));
        }*/
         for(Services__c roles: [select name from Services__c])
        {
            options.add( new SelectOption(roles.name, roles.name));
        }
        return options;
    }
    
    Public Project__c  selectedProject  {get;set;}
    id projectid ;
    //Controller 
    Public PM_ProjectAllocation(ApexPages.StandardController controller)
    {
        projectid=ApexPages.currentPage().getParameters().get('id');
        selectedProject =[Select name,id,Sales_Order__r.Deal__c from Project__c where id=:projectid][0];
        
        resetQueries();
    }
    // To get show the created project allocation records for the corresponding project
    public void resetQueries()
    {
        fetchAllocation =[Select Assigned_User__c,Role__c,Project__c,Start_Date__c, Location__c,Percentage__c,End_Date__c from Allocation__c where Project__c =:selectedProject .id ]; 
    }
    
    
    public Allocation__c  getAllocation(){
        ProjectAllocation = new Allocation__c();
        return ProjectAllocation;
    } 
    
    // To Create the project allocation 
    public pageReference Add()
    {
        try{
            if( ProjectAllocation.Assigned_User__c!=null )
            {
                
                ProjectAllocation.Project__c=selectedProject .id;
                ProjectAllocation.Role__c = selectedRole;
                database.insert(ProjectAllocation);
                ProjectAllocation = new Allocation__c();
            }
            resetQueries();
            
        }
        catch (Exception ex) {
            ApexPages.addMessages(ex);
        }
        return null;
    }
    //To delete the created project allocation record 
    public PageReference remove() 
    {
        selectedValue=ApexPages.currentPage().getParameters().get('removeRow');
        Allocation__c DeleteAllocation=new Allocation__c(id=selectedValue);
        delete DeleteAllocation ;
        resetQueries();
        return null;
        
    }
}