src/objects/Claim__c.object
<CustomObject>
    <description>Ability for employees to record and claim reimbursement from the company for official expenses incurred 
Has to capture following information</description>
    <fields>
        <fullName>Approving_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approving Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expenses_Management1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/classes/PM_ApprovalManagerSharing_TestClass.cls
@isTest
private  class PM_ApprovalManagerSharing_TestClass
{
    static Claim__c newclaim;
    static user testUser;
    public static void init()
{




}
    static testMethod void BatchableLeaveUpdate()


{

LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', No_Of_Annual_Leaves__c = 2, Frequncy_Of_Run__c='1;4;7;10' ,Active__c=True);
insert l1;
        testUser=InitializeTestData.createUser('user8@testorg.com');
database.insert(testUser);
newclaim= InitializeTestData.createClaim(testUser.id);
database.insert(newclaim);

/*List< Claim__c__Share> jShrs = [SELECT Id, UserOrGroupId, AccessLevel, 
         RowCause FROM Claim__c__share WHERE ParentId = :newclaim.Id AND UserOrGroupId= :newclaim.Approving_Manager__c]; */
      
}

}