src/objects/Claim__c.object
<CustomObject>
    <description>Ability for employees to record and claim reimbursement from the company for official expenses incurred 
Has to capture following information</description>
    <fields>
        <fullName>Approval_Comment_Check__c</fullName>
        <label>Approval Comment Check</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Claim_Items__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Claim Items</relationshipLabel>
        <relationshipName>Claim_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Claim Items</label>
    <nameField>
        <label>Claim Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/classes/PM_RequireComment_TestClass.cls
@isTest
private  class PM_RequireComment_TestClass
{
    static Claim__c newclaim;
    static user testUser;
    static Claim_Items__c claimitems;
    
    public static void init()
{
LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', No_Of_Annual_Leaves__c = 2, Frequncy_Of_Run__c='1;4;7;10' ,Active__c=True);
insert l1;
testUser=InitializeTestData.createUser('user23348@testorg.com');
database.insert(testUser);
newclaim= InitializeTestData.createClaim(testUser.id);
database.insert(newclaim);
claimitems=InitializeTestData.createClaimitems(newclaim.id);
database.insert(claimitems);
newclaim.Approval_Comment_Check__c='Requested';
database.update(newclaim);
/*
//Id testWorkItemId = generateAndSubmitObject();
        
        // Reject the submitted request, providing a comment.
        Approval.ProcessWorkitemRequest testRej = new Approval.ProcessWorkitemRequest();
        testRej.setComments('Rejecting request with a comment.');
        testRej.setAction  ('Reject');
        testRej.setWorkitemId(testWorkItemId);
    
        Test.startTest();        
            // Process the rejection
            Approval.ProcessResult testRejResult =  Approval.process(testRej);
        Test.stopTest();
        
        // Verify the rejection results
        System.assert(testRejResult.isSuccess(), 'Rejections that include comments should be permitted');
        System.assertEquals('Rejected', testRejResult.getInstanceStatus(), 
          'Rejections that include comments should be successful and instance status should be Rejected');
*/


}
    static testMethod void BatchableLeaveUpdate()


{

    
init();
/*
// Generate sample work item using utility method.
        Id testWorkItemId = generateAndSubmitObject();
        
        // Reject the submitted request, providing a comment.
        Approval.ProcessWorkitemRequest testRej = new Approval.ProcessWorkitemRequest();
        testRej.setComments('Rejecting request with a comment.');
        testRej.setAction  ('Reject');
        testRej.setWorkitemId(testWorkItemId);
    
        Test.startTest();        
            // Process the rejection
            Approval.ProcessResult testRejResult =  Approval.process(testRej);
        Test.stopTest();
        
        // Verify the rejection results
        System.assert(testRejResult.isSuccess(), 'Rejections that include comments should be permitted');
        System.assertEquals('Rejected', testRejResult.getInstanceStatus(), 
          'Rejections that include comments should be successful and instance status should be Rejected');


 
*/
}
/*
private static Id generateAndSubmitObject()
    {
        // Create a sample invoice statement object and then submit it for approval.
       // Invoice_Statement__c testIS = new Invoice_Statement__c();
        //insert testIS;
        LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', No_Of_Annual_Leaves__c = 2, Frequncy_Of_Run__c='1;4;7;10' ,Active__c=True);
insert l1;
        testUser=InitializeTestData.createUser('user8@testorg.com');
database.insert(testUser);
newclaim= InitializeTestData.createClaim(testUser.id);
database.insert(newclaim);
claimitems=InitializeTestData.createClaimitems(newclaim.id);
database.insert(claimitems);
newclaim.Approval_Comment_Check__c='Requested';
database.update(newclaim);
        
        Approval.ProcessSubmitRequest testReq = new Approval.ProcessSubmitRequest();
        testReq.setObjectId(newclaim.Id);
        Approval.ProcessResult reqResult = Approval.process(testReq);
        
        System.assert(reqResult.isSuccess(),'Unable to submit new invoice statement record for approval');
        
        return reqResult.getNewWorkitemIds()[0];
    }*/


}