src/objects/Claim__c.object
<CustomObject>
    <description>Ability for employees to record and claim reimbursement from the company for official expenses incurred 
Has to capture following information</description>
    <fields>
        <fullName>Claim_Date__c</fullName>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Claim_Number__c</fullName>
        <displayFormat>CN-{00000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Claim</relationshipLabel>
        <relationshipName>Claim</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitter_Comments__c</fullName>
        <label>Submitter Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Amount_to_Claim__c</fullName>
        <label>Total Amount to Claim</label>
        <summarizedField>Claim_Items__c.Amount_in_Claim_Currency__c</summarizedField>
        <summaryForeignKey>Claim_Items__c.Claim__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Claim_Items__c.object
<CustomObject>
    <fields>
        <fullName>Amount_in_Claim_Currency__c</fullName>
        <inlineHelpText>Amount to be reimbursed in INR</inlineHelpText>
        <label>Amount in Claim Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Claim Items</relationshipLabel>
        <relationshipName>Claim_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate1__c</fullName>
        <formula>if(Expense_Amount__c  &gt; Amount_in_Claim_Currency__c,Expense_Amount__c  /  Amount_in_Claim_Currency__c ,Amount_in_Claim_Currency__c / Expense_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenseDate__c</fullName>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <inlineHelpText>Amount paid in the Expense Currency</inlineHelpText>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense_Currency__c</fullName>
        <label>Expense Currency</label>
        <picklist>
            <picklistValues>
                <fullName>INR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MYR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <label>Expense Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel/ Commute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Claim Items</relationshipLabel>
        <relationshipName>Claim_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim Items</label>
    <nameField>
        <label>Claim Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_ClaimController.cls
public class PM_ClaimController {

    public static Claim__c claimInstance{get;set;}
    public static User userInstance{get;set;}
    public Integer Serial{get;set;}
    public PM_ClaimController(ApexPages.StandardController controller) 
    {

    }
    public void getDetails()
    {
        claimInstance = [select Id,Total_Amount_to_Claim__c,Name,OwnerId,Claim_Date__c,Project__r.Name,Submitter_Comments__c,Claim_Number__c,CurrencyIsoCode from Claim__c where Id=:ApexPages.currentPage().getParameters().get('id')];
        userInstance = [select Id,Name,EmployeeNumber from User where Id=:claimInstance.OwnerId];
        Serial = 1;
    }
    public List<Claim_Items__c> getClaimItems()
    {
        //System.assertEquals('a','b');
        //System.debug(claimInstance.Id);
        List<Claim_Items__c> liClaimItems= [select Name,Project__r.Name,Id,ExpenseDate__c,Expense_Type__c,Comments__c,Amount_in_Claim_Currency__c,Expense_Amount__c,Exchange_Rate1__c,CurrencyIsoCode,Expense_Currency__c,Exchange_Rate__c,Bill_Number__c from Claim_Items__c where Claim__c=:ApexPages.currentPage().getParameters().get('id')];
        //System.debug(liClaimItems);
        return liClaimItems;
    }

}