src/objects/Company_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Details of the Company Using this App</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beneficiary_A_c_Name__c</fullName>
        <label>Beneficiary A/c Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beneficiary_A_c_No__c</fullName>
        <label>Beneficiary A/c No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beneficiary_Bank__c</fullName>
        <label>Beneficiary Bank</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_City__c</fullName>
        <label>Company City</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Country__c</fullName>
        <label>Company Country</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Postal_Code__c</fullName>
        <label>Company Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_State__c</fullName>
        <label>Company State</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Street__c</fullName>
        <label>Company Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_1__c</fullName>
        <label>Invoice Payment Term 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_2__c</fullName>
        <label>Invoice Payment Term 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_3__c</fullName>
        <label>Invoice Payment Term 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_4__c</fullName>
        <label>Invoice Payment Term 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_5__c</fullName>
        <label>Invoice Payment Term 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_1__c</fullName>
        <label>Sales Order Payment Term 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_2__c</fullName>
        <label>Sales Order Payment Term 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_3__c</fullName>
        <label>Sales Order Payment Term 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_4__c</fullName>
        <label>Sales Order Payment Term 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_5__c</fullName>
        <label>Sales Order Payment Term 5</label>
        <type>TextArea</type>
    </fields>
    <label>Company Details</label>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price_Licenses__c</fullName>
        <label>Total Price(Licenses)</label>
        <summarizedField>Deal_Item__c.Total_Price_Licenses__c</summarizedField>
        <summaryForeignKey>Deal_Item__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Edition__c</fullName>
        <label>Product/Edition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price_Licenses__c</fullName>
        <formula>Quantity__c  *  Sales_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price(Licenses)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Percent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Tax Code</label>
</CustomObject>

src/objects/Terms_And_Conditions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <type>TextArea</type>
    </fields>
    <label>Terms And Conditions</label>
</CustomObject>

src/classes/PM_SalesOrderPDFController.cls
public class PM_SalesOrderPDFController {
    
    
    public Sales_Order__c salesOrder{get;set;}
    public Decimal totalTaxCode{get;set;}
    public Decimal totalAmount{get;set;}
    public String termsAndConditions{get;set;}
    public Decimal subtotalAmount{get;set;}
    public String AmountInWords{get;set;}
    
    public PM_SalesOrderPDFController(ApexPages.StandardController controller) 
    {
        
    }
    
    public static Company_Details__c getCompanyDetails()
    {
        Company_Details__c instance = [select Name,Company_Street__c,Company_City__c,Company_State__c,Company_Country__c,Company_Postal_Code__c,Invoice_Payment_Term_1__c,Invoice_Payment_Term_2__c,Invoice_Payment_Term_3__c,Invoice_Payment_Term_4__c,Invoice_Payment_Term_5__c,Sales_Order_Payment_Term_1__c,Sales_Order_Payment_Term_2__c,Sales_Order_Payment_Term_3__c,Sales_Order_Payment_Term_4__c,Sales_Order_Payment_Term_5__c,Beneficiary_A_c_Name__c,Beneficiary_A_c_No__c,Beneficiary_Bank__c,IFSC_Code__c from Company_Details__c where Active__c=true limit 1];
        return instance;
    }   
    
    public class PDFTaxWrapper
    {
        public Integer Serial{get;set;}
        public String TaxCode{get;set;}
        public Decimal TaxPercent{get;set;}
        public Decimal TaxAmount{get;set;}
    }
    
    public List<Deal_Item__c> getDealItems()
    {
        
        salesOrder = [select Customer__c,Deal__c,Deal__r.Total_Price_Licenses__c,Tax_Code__c,Tax_Percent__c from Sales_Order__c where Id=:ApexPages.currentPage().getParameters().get('id') limit 1];
        //Document d = [select Id,Body from Document where Document.Name='Terms & Conditions'];
        List<Deal_Item__c> var = [select Id,Product_Edition__c,List_Price__c,Sales_Price__c,Quantity__c,Total_Price_Licenses__c from Deal_Item__c where Deal__c=:salesOrder.Deal__c];
        totalAmount = salesOrder.Deal__r.Total_Price_Licenses__c; 
        subtotalAmount = salesOrder.Deal__r.Total_Price_Licenses__c;
        return var;
    }
    
    public List<PDFTaxWrapper> getTaxCode()
    {
        List<String> taxCodes = salesOrder.Tax_Code__c.split(';');
        List<String> taxPercentages = salesOrder.Tax_Percent__c.split(';');
        List<PDFTaxWrapper> listofAppliedTaxCodes = new List<PDFTaxWrapper>();
        Integer size = taxCodes.size();
        totalTaxCode=0;
        for(Integer i=0;i<size;i++)
        {
            PDFTaxWrapper AppliedTaxCodes = new PDFTaxWrapper();
            AppliedTaxCodes.Serial = i+1;
            AppliedTaxCodes.TaxCode = taxCodes[i];
            AppliedTaxCodes.TaxPercent = decimal.valueOf(taxPercentages[i]);
            AppliedTaxCodes.TaxAmount = (AppliedTaxCodes.TaxPercent*salesOrder.Deal__r.Total_Price_Licenses__c).divide(100, 2, System.RoundingMode.UP);
            totalTaxCode = totalTaxCode+AppliedTaxCodes.TaxAmount;
            listofAppliedTaxCodes.add(AppliedTaxCodes); 
        }
        totalAmount=totalAmount+totalTaxCode;
        AmountInWords=PM_Trigger_UtilityClass.generateText1(ApexPages.currentPage().getParameters().get('id'),totalAmount);
        System.debug(listofAppliedTaxCodes);
        return listofAppliedTaxCodes;
    }
    
    public List<Terms_And_Conditions__c> getTermConditions()
    {
        List<Terms_And_Conditions__c> listoftermsconditions = [select Name,Text__c from Terms_And_Conditions__c order by Name];
        return listoftermsconditions ;
    }
}