src/objects/Company_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Details of the Company Using this App</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beneficiary_A_c_Name__c</fullName>
        <label>Beneficiary A/c Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beneficiary_A_c_No__c</fullName>
        <label>Beneficiary A/c No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beneficiary_Bank__c</fullName>
        <label>Beneficiary Bank</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_City__c</fullName>
        <label>Company City</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Country__c</fullName>
        <label>Company Country</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Postal_Code__c</fullName>
        <label>Company Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_State__c</fullName>
        <label>Company State</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Street__c</fullName>
        <label>Company Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_1__c</fullName>
        <label>Invoice Payment Term 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_2__c</fullName>
        <label>Invoice Payment Term 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_3__c</fullName>
        <label>Invoice Payment Term 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_4__c</fullName>
        <label>Invoice Payment Term 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Payment_Term_5__c</fullName>
        <label>Invoice Payment Term 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_1__c</fullName>
        <label>Sales Order Payment Term 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_2__c</fullName>
        <label>Sales Order Payment Term 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_3__c</fullName>
        <label>Sales Order Payment Term 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_4__c</fullName>
        <label>Sales Order Payment Term 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Payment_Term_5__c</fullName>
        <label>Sales Order Payment Term 5</label>
        <type>TextArea</type>
    </fields>
    <label>Company Details</label>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Text__c</fullName>
        <label>Invoice Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <formula>Amount__c +  Total_Invoice_Tax_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Invoice_Quantity__c  *  Unit_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Item Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item_Name__c</fullName>
        <label>Invoice Line Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Invoice Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILIN-{0000000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Tax_Percent__c</fullName>
        <label>Tax Percent</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Tax Code</label>
</CustomObject>

src/classes/PM_InvPDFGenerationPageController.cls
public class PM_InvPDFGenerationPageController {
    //Written By Rachit
    public Decimal AmountWithTwoDecimalPlaces{get;set;}
    public Decimal TotalAmountWithTwoDecimalPlaces{get;set;}
    public Boolean invoiceTextRender{get;set;}
    public PM_InvPDFGenerationPageController(ApexPages.StandardController controller) 
    {
        Invoice__c inv = [select Invoice_Text__c from Invoice__c where Id=:ApexPages.currentPage().getParameters().get('id')];
        if(inv.Invoice_Text__c==''||inv.Invoice_Text__c==null)
        {
            invoiceTextRender =false;
        }
        else
        {
            invoiceTextRender = true;
        }
        
    }
    public static Company_Details__c getCompanyDetails()
    {
        Company_Details__c instance = [select Name,Company_Street__c,Company_City__c,Company_State__c,Company_Country__c,Company_Postal_Code__c,Invoice_Payment_Term_1__c,Invoice_Payment_Term_2__c,Invoice_Payment_Term_3__c,Invoice_Payment_Term_4__c,Invoice_Payment_Term_5__c,Sales_Order_Payment_Term_1__c,Sales_Order_Payment_Term_2__c,Sales_Order_Payment_Term_3__c,Sales_Order_Payment_Term_4__c,Sales_Order_Payment_Term_5__c,Beneficiary_A_c_Name__c,Beneficiary_A_c_No__c,Beneficiary_Bank__c,IFSC_Code__c from Company_Details__c where Active__c=true limit 1];
        return instance;
    }   
    public class PDFTaxWrapper
    {
        public Integer Serial{get;set;}
        public String TaxCode{get;set;}
        public Decimal TaxPercent{get;set;}
        public Decimal TaxAmount{get;set;}
    }
    public List<Invoice_Line_Item__c> getInvoiceLineItem()
    {
        Integer i=1;
        List<Invoice_Line_Item__c> var = [select Invoice_Line_Item_Name__c,Unit_Rate__c,Invoice_Quantity__c,Amount__c from Invoice_Line_Item__c where Invoice__c=:ApexPages.currentPage().getParameters().get('id')];
        
        return var;
    }
    
    public List<PDFTaxWrapper> getTaxCode()
    {
        Invoice__c instance = [select Tax_Code__c,Tax_Percent__c,Amount__c,Total_Invoice_Amount__c from Invoice__c where Id=:ApexPages.currentPage().getParameters().get('id')];
        AmountWithTwoDecimalPlaces = instance.Amount__c.divide(1, 2, System.RoundingMode.UP);
        TotalAmountWithTwoDecimalPlaces = instance.Total_Invoice_Amount__c.divide(1, 2, System.RoundingMode.UP);
        List<String> taxCodes = instance.Tax_Code__c.split(';');
        List<String> taxPercentages = instance.Tax_Percent__c.split(';');
        List<PDFTaxWrapper> listofAppliedTaxCodes = new List<PDFTaxWrapper>();
        Integer size = taxCodes.size();
        for(Integer i=0;i<size;i++)
        {
            PDFTaxWrapper AppliedTaxCodes = new PDFTaxWrapper();
            AppliedTaxCodes.Serial = i+1;
            AppliedTaxCodes.TaxCode = taxCodes[i];
            AppliedTaxCodes.TaxPercent = decimal.valueOf(taxPercentages[i]);
            AppliedTaxCodes.TaxAmount = (AppliedTaxCodes.TaxPercent*instance.Amount__c).divide(100, 2, System.RoundingMode.UP);
            listofAppliedTaxCodes.add(AppliedTaxCodes); 
        }
        System.debug(listofAppliedTaxCodes);
        return listofAppliedTaxCodes;
    }
    
    
}