src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Licenses</fullName>
        <active>true</active>
        <label>Licenses</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <recordTypes>
        <fullName>Licenses</fullName>
        <active>true</active>
        <label>Licenses</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>License/Edition</label>
</CustomObject>

src/classes/PM_DealItemsLicense_TestClass.cls
@isTest(seeAlldata=false)
private class PM_DealItemsLicense_TestClass {
    private static Customer__c testAccount;
    private static Connection__c testContact;
    private static Deal__c testDeal;
    private static Deal_Item__c testDealItem;
    private static License__c testLicense;
    private static Deal_Item__c testLicenseDealItem;
    
    // initializing test data
    Private static void init()
    {
        testAccount=InitializeTestData.createCustomer();
        Database.insert(testAccount);
        
        testContact=InitializeTestData.createConnection(testAccount.id);
        Database.insert(testContact);
        
        testDeal=InitializeTestData.createLicenseDeal(testAccount.id);
        Database.insert(testDeal);
        
        testLicenseDealItem=InitializeTestData.createLicenseDealItem(testDeal.id);
        testLicense=InitializeTestdata.createLicenses();
        database.insert(testLicense);
    }
    
    private static testMethod void myUnitTest() {
        init(); 
        apexpages.currentpage().getparameters().put('Dealid' , testDeal.id);
        apexpages.currentpage().getparameters().put('RecordTypeName','Licenses' );
        Test.startTest();
        PM_DealItemsLicensePageController.LicenseWrapper licensewrapperinstance= new PM_DealItemsLicensePageController.LicenseWrapper(testLicense);
        PM_DealItemsLicensePageController licenseinstance= new PM_DealItemsLicensePageController();
        licenseinstance.getDealInstance();
        licenseinstance.ListOfLicenses = licenseinstance.getListOfLicenses();
        licenseinstance.ListOfLicenses[0].selectedValues=true;
        Date startDate=Date.today();
        string startdateformat=startdate.format();
        Date endDate = startdate.addDays(2);
        string enddateformat=endDate.format();
        licenseinstance.ListOfLicenses[0].startDate =startdateformat ;
        licenseinstance.ListOfLicenses[0].endDate = enddateformat;
        licenseinstance.save();
        licenseinstance.cancel();
        licenseinstance.ListOfLicenses[0].startDate =string.valueof(Date.today());
        licenseinstance.save();
        Test.stopTest();
    }
}