src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Tax Code</label>
</CustomObject>

src/classes/PM_TaxCode_Testclass.cls
@isTest(seealldata=false)
private class PM_TaxCode_Testclass {
    
    private static Customer__c testAccount;
    private static Connection__c testContact;
    private static Deal__c testServiceDeal;
    private static Deal__c testLicenseDeal;
    private static Deal_Item__c testServiceDealItem;
    private static Deal_Item__c testLicenseDealItem;
    private static Sales_Order__c testServiceSalesOrder;
    private static Sales_Order__c testLicenseSalesOrder;
    private static Tax_Code__c testTaxCode;
    
    
    Private static void init()
    {
        testAccount=InitializeTestData.createCustomer();
        Database.insert(testAccount);
        
        testContact=InitializeTestData.createConnection(testAccount.id);
        Database.insert(testContact);
        
        testLicenseDeal=InitializeTestData.createLicenseDeal(testAccount.id);
        Database.insert(testLicenseDeal);
        
        testServiceDeal=InitializeTestData.createServiceDeal(testAccount.id);
        Database.insert(testServiceDeal);
        
        testLicenseDealItem=InitializeTestData.createLicenseDealItem(testLicenseDeal.id);
        Database.insert(testLicenseDealItem);
        
        testServiceDealItem=InitializeTestData.createServiceDealItem(testServiceDeal.id);
        Database.insert(testServiceDealItem);
        
        testServiceSalesOrder=InitializeTestData.createServiceSalesOrder(testServiceDeal.id);
        testServiceSalesOrder.Tax_Code__c='ST;GST';
        Database.insert(testServiceSalesOrder);
        
        testLicenseSalesOrder=InitializeTestData.createLicenseSalesOrder(testLicenseDeal.id,testAccount.id);
        testLicenseSalesOrder.Tax_Code__c='ST;GST';
        Database.insert(testLicenseSalesOrder);
        
        testTaxCode=InitializeTestData.createTaxCode();
        Database.insert(testTaxCode);
    }
    
    
    static testMethod void myUnitTest() {
        init();
        Boolean b=false;
        apexpages.currentpage().getparameters().put('id' , testLicenseSalesOrder.id);
        ApexPages.StandardController sc = new ApexPages.standardController(testLicenseSalesOrder);
        PM_TaxCode.TaxCodeWrapper taxWrapperInstance= new PM_TaxCode.TaxCodeWrapper(testTaxCode,b);
        PM_TaxCode taxInstance= new PM_TaxCode(sc);
        taxInstance.selectedTaxes=taxInstance.getListOfTaxes();
        taxInstance.selectedTaxes[0].selectedValues=true;
        taxInstance.save();   
    }
}