src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <formula>Sales_Order__r.Customer__r.Name</formula>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scope__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scope</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <displayFormat>Scope-{00000}</displayFormat>
        <label>Scope Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_ScopeController_Testclass.cls
@isTest(seeAlldata = true)
private class PM_ScopeController_Testclass {
    private static Customer__c testAccount;
    private static Connection__c testContact;
    private static Deal__c testDeal;
    private static Sales_Order__c testSalesorder;
    private static Project__c  testProject;
    private static scope__c testScope;
    
    Private static void init()
    {
        testAccount=InitializeTestData.createCustomer();
        Database.insert(testAccount);
        testContact=InitializeTestData.createConnection(testAccount.id);
        Database.insert(testContact);
        testDeal=InitializeTestData.createServiceDeal(testAccount.id);
        Database.insert(testDeal);
        testSalesorder=InitializeTestData.createServiceSalesOrder(testDeal.id);
        testSalesorder.Customer__c=testAccount.id;
        Database.insert(testSalesorder);
        testProject=InitializeTestData.createProject(testSalesorder.id);
        Database.insert(testProject);
        testScope=new scope__c();
        testScope.Description__c=null;
        testScope.Related_Project__c=testProject.id;
    }
    private static testMethod void myUnitTest() {
        init();
        ApexPages.StandardController sc = new ApexPages.standardController(testProject);
        // create an instance of the controller
        PM_ScopeController pm= new PM_ScopeController(sc);
        pm.getlistOfScope();
        pm.addNewScope();
        pm.addNewScope();
        database.insert(testScope);
        pm.save();
        String x=ApexPages.CurrentPage().getParameters().put('removeRow', '2');  
        pm.remove();
        String y=ApexPages.CurrentPage().getParameters().put('deleteRow', testScope.id); 
        pm.addNewScope();
        pm.addNewScope();
        pm.remove();
        /*   pm.addNewScope();
        scope__c test1= new scope__c();
        test1.Description__c='';
        test1.Related_Project__c=testProject.id;
        Database.insert(test1);
        delete test1;
        pm.save();
        pm.remove();  */
    }
}