src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_Convert_Pro_to_Cust_TestClass.cls
@isTest(seeAlldata=false)
private  class PM_Convert_Pro_to_Cust_TestClass
{
    private static Customer__c testlead;
    private static Customer__c testaccount;
    private static Connection__c testcontact;
    private static Deal__c testservicedeal;
    private static Deal__c testlicensedeal;
    
    private static void init(){
        testlead=InitializeTestData.createProspect();
        database.insert(testlead);
    }
    private static testMethod void convert(){
        init();
        PageReference pg = new PageReference('apex/PM_Convert_Prospects_To_Customers?id='+testlead.Id);
        Test.setCurrentPageReference(pg);
        PM_Convert_Prospects_To_Customers testobj=new PM_Convert_Prospects_To_Customers();
        Test.startTest();
        testobj.CreateServiceOpp=true;
        testobj.save();
        testobj.CreateLicenseOpp=true;
        testobj.save();
        testobj.hideDealTable();
        testobj.showDealTable();
        testobj.cancel();
        system.assertequals(null,testobj.hideDealTable());
        Test.stopTest();
    }
}