src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_leaves_to_be_carry_forward__c</fullName>
        <label>No. of leaves to be carry forward</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LM_LeaveCarryForwardToNextYear_TestClass.cls
@isTest
private  class  LM_LeaveCarryForwardToNextYear_TestClass
{
    
    private static user newuser;
    //public static LM_CustomSetting__c CreateLeaveAllocation;
    
    public static void init()
    {
        
        newuser =InitializeTestData.createUser('user4@testorg.com');
        database.insert(newuser );
        
        //CreateLeaveAllocation =InitializeTestData.LeaveAllocation();
        //database.insert(CreateLeaveAllocation );
        
        
    }
    static testMethod void BatchableCarryforward()
    {
        LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', Frequncy_Of_Run__c = '1;4;7;10', No_Of_Annual_Leaves__c=2,No_of_leaves_to_be_carry_forward__c=4 ,Active__c=True);
        insert l1 ;
        
        Test.StartTest();
        
        init();
        
        LM_LeaveCarryForwardToNextYear lm= new LM_LeaveCarryForwardToNextYear ();
        
        //lm.query ='Select id,name, Total_Leave__c from Contact where AccountId =acc.Id AND Exit_Date__C= NULL' ;
        ID batchid = Database.executeBatch(lm);
        Test.StopTest();
        
        //Test.StopTest();
    }
}