src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LOP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_LOP__c</fullName>
        <label>Number of Days(LOP)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Leave__c</fullName>
        <label>Reason for Leave</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Working_days__c</fullName>
        <label>No. Leaves Applied</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{00000}</displayFormat>
        <label>Leave Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <label>Reports to Manager</label>
        <relationshipName>ProjectLead1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Reports_to_ManagerHR__c</fullName>
        <label>Reports to Manager /HR</label>
        <relationshipName>Reports_to_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LM_ApplicationLeaveClass.cls
global class LM_ApplicationLeaveClass {
    
    public Leave_Request__c leaveRequestRecord;
    public User users{get;set;}
    public list<Leave_Request__c> leaveRequestFetch{get;set;}
    Integer allDaysBetween;
    public  Leave_Request__c getLeave(){
        leaveRequestRecord = new Leave_Request__c();
        return leaveRequestRecord;
    } 
    
    
    public LM_ApplicationLeaveClass (ApexPages.StandardController controller) {
        resetQueries();
    }
    
    public void resetQueries(){
        id userId ;
        userId  = ApexPages.currentPage().getParameters().get('conid');
        if(userId  == null){
            userId  = UserInfo.getUserId();
        }
        users=[select id, name,Project_Lead__c,Total_Leave__c,Reports_to_ManagerHR__c  from user where id=:userId][0];
        leaveRequestFetch=[select id,Name,Employee__c,Project_Lead__c, Start_Date__c, End_Date__c, Status__c, LOP__c ,Number_of_Days_LOP__c, Total_Working_days__c, Reason_for_Leave__c from Leave_Request__c where Employee__c= :userId   and END_Date__c = THIS_YEAR order by Start_Date__c desc];
    }
    
    
    public pageReference save()
    {
        try{
            Decimal totalLeaves;
            leaveRequestRecord.Employee__c=users.id;
            leaveRequestRecord.Project_Lead__c=users.Project_Lead__c;
            Database.saveResult result = database.insert(leaveRequestRecord);
            if(result.success){
                Leave_Request__c insertedRec = [select LOP__c,Number_of_Days_LOP__c from Leave_Request__c where Id = :result.id];
                if(insertedRec .LOP__c){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Leave applied sucessfully.' + insertedRec.Number_of_Days_LOP__c +' day(s) has/have been marked as LOP. Contact HR for more details'));
                }
                else{
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Leave applied sucessfully'));
                }
                resetQueries();
                
            }
            
            return null;
            
        }
        catch (Exception ex) {
            ApexPages.addMessages(ex);
            return null;
        }
    }
    
    
}