src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Id. Decision Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perception Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Price_Licenses__c</fullName>
        <label>Total Price(Licenses)</label>
        <summarizedField>Deal_Item__c.Total_Price_Licenses__c</summarizedField>
        <summaryForeignKey>Deal_Item__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Edition__c</fullName>
        <label>Product/Edition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Price_Licenses__c</fullName>
        <formula>Quantity__c  *  Sales_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price(Licenses)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer_Price__c</fullName>
        <label>Transfer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer_Price__c</fullName>
        <label>Transfer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>License/Edition</label>
</CustomObject>

src/classes/PM_DealItemsLicensePageController.cls
public class PM_DealItemsLicensePageController {
    /*
Description of the class:
Author:satyanarayana
Created:06/02/2013
Modified Date + Things Modified:
1 . 25/3/2013 - Commenting code and reviewing

Code Review results:

*/
    
    String license_DealId=Apexpages.currentPage().getParameters().get('Dealid');
    String license_DealRecordTypeName=Apexpages.currentPage().getParameters().get('RecordTypeName');
    String deal_ObjectId= Schema.SObjectType.Deal__c.getKeyPrefix();
    public List<LicenseWrapper> ListOfLicenses;
    public list<LicenseWrapper> selectedLicenses;
    public List<Deal_Item__c> listOfDealitems=new List<Deal_Item__c>();
    public Deal__c dealValue;
    
    //Constructor querying the Customsetting of type 'License'.
    public PM_DealItemsLicensePageController() {
        
        ListOfLicenses= new List<LicenseWrapper>();
        for(License__c LicenseDetail: [select Id, Name,List_Price__c,Transfer_Price__c from License__c order by List_Price__c asc]) {
            ListOfLicenses.add(new LicenseWrapper(LicenseDetail));
        }
    } 
    
    public Deal__c getDealInstance() {
        //dealValue=new Deal__c ();
        dealValue=[select id,name,Customer__c,Stage__c,Total_Price_Licenses__c,Close_Date__c,CurrencyISOCode,Deal_Start_Date__c,Deal_End_Date__c from Deal__c where id=:license_DealId limit 1];
        return dealValue;
    }
    
    public List<LicenseWrapper> getListOfLicenses() {
        
        return ListOfLicenses;
    } 
    
    //Wrapper class  to display custom settings.
    public class LicenseWrapper{
        Public Boolean selectedValues{get;set;}
        Public String Name {get;set;}
        Public Decimal listPrice{get;set;}
        Public Decimal transferPrice{get;set;}
        public Integer Quantity{get;set;}
        public Decimal salesPrice{get;set;} 
        public String startDate{get;set;}
        public String endDate{get;set;} 
        
        
        public LicenseWrapper(License__c license){
            
            selectedValues=false;
            Name =license.name;
            listPrice=license.List_Price__c;
            transferPrice=license.Transfer_Price__c ;
            Quantity=null;
            salesPrice=null;
            startDate=null;
            endDate=null;
        }
    }
    
    //Saving the Deal lineitems to particular Deal.
    public  pagereference save(){
        selectedLicenses= new List<LicenseWrapper>();
        for(LicenseWrapper LicenseInstance:getListOfLicenses()) {
            
            if(LicenseInstance.selectedValues== true) {
                Deal_Item__c dealItem = new Deal_Item__c();
                dealItem.Deal__c=Apexpages.currentPage().getParameters().get('Dealid');
                dealItem.Product_Edition__c = LicenseInstance.Name ;
                try{
                    dealItem.Quantity__c=LicenseInstance.Quantity;
                    dealItem.Sales_Price__c=LicenseInstance.salesPrice;
                    dealItem.Transfer_Price__c=LicenseInstance.transferPrice;
                }catch(Exception e){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,e.getMessage());
                    ApexPages.addMessage(myMsg);
                    return null;
                }
                try{
                    dealItem.Start_Date__c=date.parse(LicenseInstance.startDate);
                    dealItem.End_Date__c=date.parse(LicenseInstance.endDate);
                }
                catch(Exception e){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Date format is invalid or blank');
                    ApexPages.addMessage(myMsg);
                    listOfDealItems.clear();
                    return null;
                }
                if(dealItem.Start_Date__c>dealItem.End_Date__c){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Start Date should be lessthan End Date');
                    ApexPages.addMessage(myMsg);
                    return null;
                }
                
                dealItem.List_Price__c=LicenseInstance.listPrice;
                RecordType recordTypeName=[select Id,Name from RecordType where SobjectType = 'Deal_Item__c' AND Name=:license_DealRecordTypeName];
                dealItem.RecordTypeId=recordTypeName.id;
                dealItem.CurrencyIsoCode=dealValue.CurrencyIsoCode;
                // inv.CurrencyIsoCode = listOfMilestones[0].Sales_Order__r.CurrencyIsoCode;
                listOfDealItems.add(dealItem);
                
            }
        }
        try{
            
            database.insert(listOfDealitems);
            pagereference pr= new pagereference('/'+ license_DealId);
            return pr;
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage());
            ApexPages.addMessage(myMsg);
        }
        
        return null;
    }
    
    public PageReference cancel() {
        pagereference pr= new pagereference('/'+license_DealId);
        return pr;
    }
}