src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Client_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_createNewDeal_TestClass.cls
@isTest
private class  PM_createNewDeal_TestClass {
    private static Customer__c NewCustomer;
    private static Deal__c NewDeal;
    
    
    Private static void init()
    {
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createLicenseDeal(NewCustomer.id);
        database.insert(NewDeal);
        
        
    }
    
    private static testMethod void myUnitTest() {
        init(); 
        NewDeal.Client_Renewal__c=true;
        update NewDeal;
        
    }
}