src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Id. Decision Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perception Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Hours__c</fullName>
        <label>Total Estimated Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price_Services__c</fullName>
        <label>Total Price(Services)</label>
        <summarizedField>Deal_Item__c.Total_Price_Services__c</summarizedField>
        <summaryForeignKey>Deal_Item__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effort_Days__c</fullName>
        <inlineHelpText>No.of Days</inlineHelpText>
        <label>Effort Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>percent__c</fullName>
        <formula>IF(And(!ISBLANK(Start_Date__c),!ISBLANK(End_Date__c),(Start_Date__c= End_Date__c )),(Effort_Days__c/1),
IF(And(!ISBLANK(Start_Date__c),!ISBLANK(End_Date__c),!ISBLANK(Effort_Days__c)), 
(Effort_Days__c/((End_Date__c- Start_Date__c)+1)),0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allocation percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Services</label>
</CustomObject>

src/classes/PM_CreateResourceForecast.cls
public class PM_CreateResourceForecast {
    
    // public String countrycode { get; set; }
    String currencyvalue;
    //String slectedvalue{get;set;}
    
    public Deal__c getDealServiceInstance() {
        Deal__c dealValues=[select id,name,Customer__c,Stage__c,Total_Price_Services__c ,Total_Estimated_Hours__c,Close_Date__c,Deal_Start_Date__c,Deal_End_Date__c from Deal__c where id=:Apexpages.currentPage().getParameters().get('id')];
        return dealValues;
    }
    
    
    //String service_DealId=Apexpages.currentPage().getParameters().get('Dealid');
    //String service_DealRecordTypeName=Apexpages.currentPage().getParameters().get('RecordTypeName');
    //String deal_ObjectId= Schema.SObjectType.Deal__c.getKeyPrefix();
    
    public List<ServiceWrapper> ListOfServices;
    public list<ServiceWrapper> selectedServices;
    public List<Resource_Forecast__c> listOfResourceForecasts=new List<Resource_Forecast__c>();
    List<SelectOption> options = new List<SelectOption>();
    public List<CurrencyType> currencyCode;
    public List<ServiceWrapper> getListOfServices() {
        
        return ListOfServices;
    }
    
    
    
    
    public PM_CreateResourceForecast() {
        
        ListOfServices= new List<ServiceWrapper>();
        for(Services__c listOflic: [select Id, Name,Unit_Rate__c from Services__c ORDER BY Name desc]) {
            ListOfServices.add(new ServiceWrapper(listOflic));
        }
        
    } 
    
    public class ServiceWrapper{
        Public Boolean selectedValues{get;set;}
        Public String Name {get;set;}
        public String unitMeasure {get;set;}
        Public Decimal UnitRate{get;set;}
        public Integer Quantity{get;set;}
        public String StartDate{get;set;}
        public String EndDate{get;set;}
        public String countrycode{get;set;}
        
        public ServiceWrapper(Services__c services)
        {
            
            selectedValues=false;
            Name =services.name;
            UnitRate=services.unit_Rate__c;
            Quantity=null;
            unitMeasure=null;
            StartDate=null;
            EndDate=null;
            countrycode=null;
            // salesPrice=0;
        }
    }
    public void selectedValues()
    {
        selectedServices= new List<ServiceWrapper>();
        for(ServiceWrapper services:getListOfServices()) {
            if(services.selectedValues== true) {
                selectedServices.add(services);
                system.debug('-------------------------------------------- INSIDESAVE12');
                system.debug(selectedservices);
            }
        }
        
    }
    
    public List<SelectOption> getlistCurrencyCode() 
    {
        options.clear();
        currencyCode = [select IsoCode,IsActive from CurrencyType where IsActive=true]; 
        if (currencyCode.Size() >0)
        {
            //options.add(new SelectOption('--None--','--None--'));
            for( CurrencyType s:currencyCode)
            {
                if (s.IsoCode != null)
                    
                    options.add(new SelectOption(s.IsoCode,s.IsoCode));
            }
        }
        return options;
    }
    
    
    
    public  pagereference save(){
        try{
            
            selectedValues();
            system.debug('-------------------------------------------- INSIDESAVE');
            //selectedServices= new List<ServiceWrapper>();
            
            
            for(ServiceWrapper serviceInstance:getListOfServices()) {
                
                system.debug('-------------------------------------------- INSIDeForloop');
                if(serviceInstance.selectedValues== true) {
                    //selectedProducts.add(products);
                    system.debug('-------------------------------------------- INSIDEF'+serviceInstance.selectedValues);
                    Resource_Forecast__c ResourceForecast = new Resource_Forecast__c();
                    ResourceForecast .Unit_Rate__c=serviceInstance.UnitRate;
                    ResourceForecast.Deal__c=ApexPages.currentPage().getParameters().get('id');
                    ResourceForecast.Role__c = serviceInstance.Name ;
                    ResourceForecast.Quantity__c=serviceInstance.Quantity;
                    // RecordType recordTypeName=[select Id,Name from RecordType where SobjectType = 'Resource_Forecast__c' AND Name=:service_DealRecordTypeName];
                    //ResourceForecast.RecordTypeId=recordTypeName.id;
                    // try{
                    ResourceForecast.Start_Date__c=Date.parse(serviceInstance.StartDate);
                    ResourceForecast.End_Date__c=Date.parse(serviceInstance.EndDate);
                    /*  }Catch(Exception e) {
ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Date format is invalid or blank');
ApexPages.addMessage(myMsg);
} */
                    
                    ResourceForecast.Unit__c=serviceInstance.unitMeasure;
                    ResourceForecast.CurrencyIsoCode=serviceInstance.countrycode;
                    /* if(ResourceForecast.Start_Date__c!=null&&ResourceForecast.End_Date__c!=null&&){
ResourceForecast.Effort_Days__c=1;
}*/
                    if(ResourceForecast.Start_Date__c!=null&&ResourceForecast.End_Date__c!=null){
                        ResourceForecast.Effort_Days__c=ResourceForecast.Start_Date__c.daysBetween(ResourceForecast.End_Date__c)+1;
                        //ResourceForecast.Percent__c=100;
                        
                    }
                    listOfResourceForecasts.add(ResourceForecast);
                }
            }
            
            
            database.insert(listOfResourceForecasts);
        }catch(Exception e){ 
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
            listOfResourceForecasts.clear();
            return null;
        }
        pagereference pr= new pagereference('/'+Apexpages.currentPage().getParameters().get('id'));
        return pr;
    } 
    
    public PageReference cancel() {
        pagereference pr= new pagereference('/'+Apexpages.currentPage().getParameters().get('id'));
        return pr;
    }
    
}