src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar - Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar - Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of mouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Data List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Opps - Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reema&apos;s List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle DB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <recordTypes>
        <fullName>Prospects</fullName>
        <active>true</active>
        <description>People possible to become Clients.</description>
        <label>Prospects</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_WebtoLead.cls
public class PM_WebtoLead {
    /*
Description of the class:
Author:satyanarayana
Created:12/02/2013
Modified Date + Things Modified:
1 . 25/3/2013 -Fixed abug regarding email field, which is unique & Commenting code and reviewing.

Code Review results:

*/
    
    public Customer__c cust;
    
    public PM_WebtoLead(ApexPages.StandardController controller) {
        this.cust= (Customer__c)controller.getRecord();
        cust.Source__c='Web';
        cust.RecordTypeId = [select Id from RecordType where SobjectType ='Customer__c' and Name ='Prospects'].Id;
    }
    
    //Save the record if the email provided by user is unique.
    public pagereference save(){
        
        try{
            insert cust;
            pagereference pr= new pagereference('http://www.extentor.com');
            return pr; 
            
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message (ApexPages.Severity.error,'Your email is already registered with us.'));
        }
        return null;
    }
    
    public pagereference cancel(){
        pagereference pr= new pagereference('http://www.extentor.com');
        return pr;
    }
    
}