src/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Address_To_Shipping_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Billing Address To Shipping Address</label>
        <type>Checkbox</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_CopyAddress_TestClass.cls
@isTest(seeAlldata = true)
private  class PM_CopyAddress_TestClass
{
    private static Customer__c testaccount;
    private static testMethod void copyAddress(){
        testaccount =InitializeTestData.createCustomer();
        database.insert(testaccount);
        
        testaccount.Billing_Address_To_Shipping_Address__c=true;
        database.update(testaccount);
        System.assertEquals(true, testaccount.Billing_Address_To_Shipping_Address__c);
        
    }
}