src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_GenerateSOPDF_TestClass.cls
@isTest(seeAlldata = false)
private class PM_GenerateSOPDF_TestClass
{
    static User testUser;
    static Customer__c testCompany;
    static Deal__c testDeal;
    static Deal_Item__c testDealItem1;
    static Deal_Item__c testDealItem2;
    static Sales_Order__c testSalesOrder;
    
    public static void init()    
    {
        
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        
        testUser=InitializeTestData.createUser('user15@testorg.com');
        testUser.EmployeeNumber = '1234234344';
        database.insert(testUser);
        testCompany=InitializeTestData.createCustomer();
        testCompany.Name='ClientCompany';
        database.insert(testCompany);
        testDeal=InitializeTestData.createLicenseDeal(testCompany.Id);
        database.insert(testDeal);
        testSalesOrder=InitializeTestData.createLicenseSalesOrder(testDeal.Id,testCompany.Id);
        database.insert(testSalesOrder);
        
    }
    static testmethod void generatecheckSO()
    {
        init();
        Test.startTest();
        String isCheck = PM_Generate_and_Attach_SO_PDF1.Generate(testSalesOrder.Id);
        System.assertEquals(isCheck,'success');
        Test.stopTest();
    }
}