src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Date__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Account</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Invoice</label>
        <referenceTo>Supplier_Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>PO_Issued_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Issued By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Account</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Supplier_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Supplier Invoices</relationshipLabel>
        <relationshipName>Supplier_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Invoice</label>
    <nameField>
        <label>Supplier Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_Payment_TestClass.cls
@isTest(seeAlldata = false)
private class PM_Payment_TestClass
{
    static User testUser;
    static Customer__c testSupplier;
    static Purchase_Order__c testPurchaseOrder;
    static Supplier_Invoice__c testSupplierInvoice;
    
    public static void init()
    {
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        testUser=InitializeTestData.createUser('user18@testorg.com');
        testUser.EmployeeNumber = '35254243';
        database.insert(testUser);
        testSupplier=InitializeTestData.createSupplier();
        database.insert(testSupplier);
        testPurchaseOrder=InitializeTestData.createPurchaseOrder();
        testPurchaseOrder.PO_Issued_By__c = testUser.Id;
        database.insert(testPurchaseOrder);
        testSupplierInvoice=InitializeTestData.createSupplierInvoice();
        testSupplierInvoice.Customer__c = testSupplier.Id;
        testSupplierInvoice.Purchase_Order__c = testPurchaseOrder.Id;
        database.insert(testSupplierInvoice);
    }
    static testmethod void checkPaymentPageCHEQUE()
    {
        init();
        
        Payment__c newPayment = new Payment__c();
        newPayment.Supplier_Account__c = testSupplier.Id;
        newPayment.Payment_Date__c = date.today();
        newPayment.Payment_Due_Date__c = date.today();
        newPayment.Amount_Paid__c = 12334556;
        newPayment.Payment_Mode__c = 'Cheque';
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_PaymentPage');
        Test.setCurrentPageReference(pg);
        
        ApexPages.StandardController sc = new ApexPages.standardController(newPayment);
        //sc.setRecord(newPayment);
        PM_PaymentPageController controller = new PM_PaymentPageController(sc);
        controller.dispSection();
        Test.stopTest();
        
    }
    static testmethod void checkPaymentPageCASH()
    {
        init();
        Payment__c newPayment = new Payment__c();
        newPayment.Supplier_Account__c = testSupplier.Id;
        newPayment.Payment_Date__c = date.today();
        newPayment.Payment_Due_Date__c = date.today();
        newPayment.Amount_Paid__c = 12334556;
        newPayment.Payment_Mode__c = 'Cash';
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_PaymentPage');
        Test.setCurrentPageReference(pg);
        
        ApexPages.StandardController sc = new ApexPages.standardController(newPayment);
        //sc.setRecord(newPayment);
        PM_PaymentPageController controller = new PM_PaymentPageController(sc);
        controller.dispSection();
        Test.stopTest();
        
    }
    static testmethod void checkPaymentPageBANKTRANSFER()
    {
        init();
        Payment__c newPayment = new Payment__c();
        newPayment.Supplier_Account__c = testSupplier.Id;
        newPayment.Payment_Date__c = date.today();
        newPayment.Payment_Due_Date__c = date.today();
        newPayment.Amount_Paid__c = 12334556;
        newPayment.Payment_Mode__c = 'Bank Transfer';
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_PaymentPage');
        Test.setCurrentPageReference(pg);
        
        ApexPages.StandardController sc = new ApexPages.standardController(newPayment);
        //sc.setRecord(newPayment);
        PM_PaymentPageController controller = new PM_PaymentPageController(sc);
        controller.dispSection();
        Test.stopTest();
    }
    static testmethod void checkPaymentPage()
    {
        init();
        Payment__c newPayment = new Payment__c();
        newPayment.Supplier_Account__c = testSupplier.Id;
        newPayment.Payment_Date__c = date.today();
        newPayment.Payment_Due_Date__c = date.today();
        newPayment.Amount_Paid__c = 12334556;
        
        Test.startTest();
        PageReference pg = new PageReference('/apex/PM_PaymentPage');
        Test.setCurrentPageReference(pg);
        
        ApexPages.StandardController sc = new ApexPages.standardController(newPayment);
        //sc.setRecord(newPayment);
        PM_PaymentPageController controller = new PM_PaymentPageController(sc);
        controller.dispSection();
        Test.stopTest();
    }
}