src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Services</label>
</CustomObject>

src/classes/PM_CreateResourceForecast_TestClass.cls
@isTest
private class  PM_CreateResourceForecast_TestClass {
    private static Customer__c NewCustomer;
    private static Deal__c NewDeal;
    private static  Resource_Forecast__c NewResource_Forecast;
    private static Services__c testService;
    
    Private static void init()
    {
        NewCustomer = InitializeTestData.createCustomer();
        database.insert(NewCustomer);
        NewDeal=InitializeTestData.createServiceDeal(NewCustomer.id);
        database.insert(NewDeal);
        NewResource_Forecast=InitializeTestData.CreateResource_Forecast(NewDeal.id);
        database.insert(NewResource_Forecast);
        testService=InitializeTestdata.createServices();
        database.insert(testService); 
        
    }
    
    private static testMethod void myUnitTest() {
        init(); 
        
        pagereference pr=new pagereference('/apex/PM_ResourceForecastOnDeal?id='+NewDeal.id);
        Test.setCurrentPageReference(pr);
        Apexpages.StandardController sc = new Apexpages.standardController(NewDeal);
        
        PM_CreateResourceForecast.ServiceWrapper serviceInstance= new PM_CreateResourceForecast.ServiceWrapper(testService);
        PM_CreateResourceForecast services= new PM_CreateResourceForecast ();
        
        services.getDealServiceInstance();
        services.ListOfServices = services.getListOfServices();
        services.ListOfServices[0].selectedValues = true;
        services.selectedValues();
        services.save();
        
        services.cancel();
        
    }
    
}