src/objects/Customer__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Id. Decision Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perception Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Hours__c</fullName>
        <label>Total Estimated Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price_Services__c</fullName>
        <label>Total Price(Services)</label>
        <summarizedField>Deal_Item__c.Total_Price_Services__c</summarizedField>
        <summaryForeignKey>Deal_Item__c.Deal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Item</relationshipLabel>
        <relationshipName>Deal_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Price_Services__c</fullName>
        <formula>Quantity__c  *  Unit_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price(Services)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Deal Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Services</label>
</CustomObject>

src/classes/PM_DealItemsServicePageController.cls
public class PM_DealItemsServicePageController {
    /*
Description of the class:
Author:satyanarayana
Created:06/02/2013
Modified Date + Things Modified:
1 . 25/3/2013 - Commenting code and reviewing

Code Review results:

*/
    
    public List<ServiceWrapper> ListOfServices;
    public list<ServiceWrapper> selectedServices;
    public List<Deal_Item__c> listOfDealitems=new List<Deal_Item__c>();
    String service_DealId=Apexpages.currentPage().getParameters().get('Dealid');
    String service_DealRecordTypeName=Apexpages.currentPage().getParameters().get('RecordTypeName');
    String deal_ObjectId= Schema.SObjectType.Deal__c.getKeyPrefix();
    
    
    //Constructor querying the Customsetting of type 'Service'.
    public PM_DealItemsServicePageController() {
        
        ListOfServices= new List<ServiceWrapper>();
        for(Services__c listOflic: [select Id, Name,Unit_Rate__c from Services__c]) {
            ListOfServices.add(new ServiceWrapper(listOflic));
        }
    } 
    
    
    public Deal__c getDealServiceInstance() {
        Deal__c dealValues=[select id,name,Customer__c,Stage__c,Total_Price_Services__c ,Total_Estimated_Hours__c,Close_Date__c,Deal_Start_Date__c,Deal_End_Date__c from Deal__c where id=:service_DealId limit 1];
        return dealValues;
    }
    
    
    
    
    public List<ServiceWrapper> getListOfServices() {
        
        return ListOfServices;
    }
    
    //Wrapper class  to display custom settings.
    public class ServiceWrapper{
        Public Boolean selectedValues{get;set;}
        Public String Name {get;set;}
        public String unitMeasure {get;set;}
        Public Decimal UnitRate{get;set;}
        public Integer Quantity{get;set;}
        
        
        public ServiceWrapper(Services__c services){
            selectedValues=false;
            Name =services.name;
            UnitRate=services.unit_Rate__c;
            Quantity=null;
            unitMeasure=null;
        }
    }
    public void selectedValues(){
        selectedServices= new List<ServiceWrapper>();
        for(ServiceWrapper services:getListOfServices()) {
            if(services.selectedValues== true) {
                selectedServices.add(services);
                system.debug(selectedservices);
            }
        }
    }
    
    //Saving the Deal lineitems to particular Deal.
    public  pagereference save(){
        selectedServices= new List<ServiceWrapper>();
        for(ServiceWrapper serviceInstance:getListOfServices()) {
            if(serviceInstance.selectedValues== true) {
                Deal_Item__c dealItem = new Deal_Item__c();
                dealItem .Unit_Rate__c=serviceInstance.UnitRate;
                dealItem.Deal__c=ApexPages.currentPage().getParameters().get('Dealid');
                dealItem.Role__c = serviceInstance.Name ;
                dealItem.Quantity__c=serviceInstance.Quantity;
                RecordType recordTypeName=[select Id,Name from RecordType where SobjectType = 'Deal_Item__c' AND Name=:service_DealRecordTypeName];
                dealItem.RecordTypeId=recordTypeName.id;
                dealItem.Unit__c=serviceInstance.unitMeasure;
                listOfDealItems.add(dealItem);
            }
        }
        try{
            database.insert(listOfDealitems);
        }catch(Exception e){ 
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
            return null;
        }
        pagereference pr= new pagereference('/'+service_DealId);
        return pr;
    } 
    
    public PageReference cancel() {
        pagereference pr= new pagereference('/'+ service_DealId);
        return pr;
    }
    
}