src/objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Resource Forecasts</relationshipLabel>
        <relationshipName>Resource_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effort_Days__c</fullName>
        <inlineHelpText>No.of Days</inlineHelpText>
        <label>Effort Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>percent__c</fullName>
        <formula>IF(And(!ISBLANK(Start_Date__c),!ISBLANK(End_Date__c),(Start_Date__c= End_Date__c )),(Effort_Days__c/1),
IF(And(!ISBLANK(Start_Date__c),!ISBLANK(End_Date__c),!ISBLANK(Effort_Days__c)), 
(Effort_Days__c/((End_Date__c- Start_Date__c)+1)),0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allocation percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Resource Forecast</label>
    <nameField>
        <displayFormat>RF-{000000}</displayFormat>
        <label>Resource Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Services</label>
</CustomObject>

src/classes/PM_Resource_Forecast_Edit.cls
public class PM_Resource_Forecast_Edit {
    
    public Resource_Forecast__c resourceForecastInstance {get;set;}
    public Resource_Forecast__c resourceForecast;
    List<SelectOption> options = new List<SelectOption>();
    public List<Services__c> serviceInfo ;
    
    
    
    public PM_Resource_Forecast_Edit(ApexPages.StandardController controller) {
        
        resourceForecast = (Resource_Forecast__c)controller.getRecord();
        resourceForecastInstance =[select name,Effort_Days__c,Percent__c,Start_Date__c,End_Date__c,Deal__c,Quantity__c,role__c,Unit__c,Unit_Rate__c from Resource_Forecast__c where id=:resourceForecast.id] ; 
        
    }
    
    public List<SelectOption> getRole() 
    {
        options.clear();
        serviceInfo = [select name,Unit_Rate__c from Services__c]; 
        if (serviceInfo.Size() >0)
        {
            options.add(new SelectOption('--None--','--None--'));
            for(Services__c s:serviceInfo)
            {
                if (s.name != null)
                    
                    options.add(new SelectOption(s.name,s.name));
            }
        }
        return options;
    }
    public pagereference save(){
        update resourceForecastInstance ;
        pagereference pr= new pagereference('/'+resourceForecastInstance.deal__c);
        return pr;
    }
    
    public pagereference ChangeValue(){
        if(resourceForecastInstance.role__c!='--None--'){
            resourceForecastInstance.Unit_Rate__c=[select name,Unit_Rate__c from Services__c where name=:resourceForecastInstance.role__c].Unit_Rate__c;
        }else
            resourceForecastInstance.Unit_Rate__c=0.0;
        return null;
    } 
}