src/objects/DemoOrgs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>DemoOrgs</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/IndiaDemoOrgsController_Test.cls
@isTest(seeAllData=false)
public class IndiaDemoOrgsController_Test{
    private static List<DemoOrgs__c > demoOrgsList;
    static void init(){
    demoOrgsList=new List<DemoOrgs__c>();
        for(integer i=0;i<10;i++){
        	DemoOrgs__c d=new DemoOrgs__c(Name='test'+i,Industry__c='industryTest'+i,User_Name__c='user'+i,Password__c='password'+i);
            demoOrgsList.add(d);
        }
        database.insert(demoOrgsList);
    
    }
    private static testmethod void demoOrgsLoginUnitTest(){
    		init();
        IndiaDemoOrgsController demoOrgsCtrl=new IndiaDemoOrgsController ();
        demoOrgsCtrl.demoOrg=new DemoOrgs__c(Name='Test');
        System.assertEquals(demoOrgsCtrl.saveNewOrg(), null);
        System.assertEquals(demoOrgsCtrl.showNew(),null);
    }
}