src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Validation</label>
        <type>Checkbox</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{00000}</displayFormat>
        <label>Leave Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/classes/LM_SubmitforApproval_TestClass.cls
@isTest(SeeAllData=false)
private class LM_SubmitforApproval_TestClass{
    private static user testuser;
    private static user testuser2;
    private static Leave_Request__c testleave;
    private static Testmethod void createLeaveRequest()
    {
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        
        testuser= InitializeTestData.createUser('user7@testorg.com');
        database.insert(testuser);
        
        testuser2=InitializeTestData.createManagerUser(testuser.id);
        database.insert(testuser2);
        
        testleave = InitializeTestData.createLeaveRequest(testuser2.id,date.newInstance(date.today().year(),02,16),date.newInstance(date.today().year(),02,17));
        testleave.Employee__c=testuser2.id;
        testleave.Override_Validation__c=false;
        Test.startTest();
        database.insert(testleave);
        Test.stopTest();
        processinstance p  = [SELECT TargetObjectId FROM ProcessInstance WHERE TargetObjectId = :testleave.Id];    
    }
}