src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_Joining__c</fullName>
        <label>Date of Joining</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/LM_User_BI_TestClass.cls
@isTest
private class LM_User_BI_TestClass {
    private static user testUser;
    
    
    static testMethod void myUnitTest() {
        LM_CustomSetting__c custominstance= new LM_CustomSetting__c();
        custominstance.name='testing';
        custominstance.Active__c=true;
        custominstance.No_Of_Annual_Leaves__c=21;
        custominstance.Frequncy_Of_Run__c='1;4;7;9';
        insert custominstance;
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs (thisUser) {
            // String extentorAccountid = [Select id from userrole  where name='Developer'  limit 1].id;
            testUser=InitializeTestData.createUser('user9@testorg.com');
            // testUser.UserRoleId=extentorAccountid;
            testUser.Date_of_Joining__c=date.today();
            Database.insert(testUser);
        }
        custominstance.Frequncy_Of_Run__c='0';
        database.update(custominstance);
        System.runAs (thisUser) {
            // String extentorAccountid = [Select id from userrole  where name='Developer'  limit 1].id;
            testUser=InitializeTestData.createUser('user10@testorg.com');
            testUser.UserName='testtrigger@extentor.com';
            // testUser.UserRoleId=extentorAccountid;
            testUser.Date_of_Joining__c=date.today();
            Database.insert(testUser);
        }
    }
}