src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/classes/LM_ScheduledBirthdayUpdateTestClass.cls
@isTest(SeeAllData=false)
private  class  LM_ScheduledBirthdayUpdateTestClass
{
    static testMethod void SchedulerBirthday()
    {
        Test.StartTest();
        
        //LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', Frequncy_Of_Run__c = '1;4;7;10', No_Of_Annual_Leaves__c=2 ,Active__c=True);
        //insert l1;
        LM_Scheduledbirthday  sh1 = new LM_Scheduledbirthday  ();
       // sh1.monthToConsider = 1;
       // sh1.dateToConsider = date.newinstance(date.today().year(),01,01);
        String sch = '0 0 23 * * ?';
        system.schedule('Test', sch, sh1);
        Test.stopTest();
    }
}