src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LM_UpdateLeaveBalance_TestClass.cls
@isTest
private  class LM_UpdateLeaveBalance_TestClass
{
    static user testUser;
    static testMethod void BatchableLeaveUpdate()
{
if(Test.isRunningTest()){ 
    
 LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', No_Of_Annual_Leaves__c = 2, Frequncy_Of_Run__c='1;4;7;10' ,Active__c=True);
insert l1;
testUser=InitializeTestData.createUser('user8@testorg.com');
database.insert(testUser);
testUser.Total_Leave__c=21;
database.update(testUser);
Test.StartTest();
LM_UpdateLeaveBalance lm= new LM_UpdateLeaveBalance();
lm.ContactList='select name,Total_Leave__c,Email from user where name=\'Testing\'';
ID batchid = Database.executebatch(lm);
   Test.StopTest();
   }

}
}