src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_leaves_to_be_carry_forward__c</fullName>
        <label>No. of leaves to be carry forward</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_Joining__c</fullName>
        <label>Date of Joining</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Leave__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Leave</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/LM_LeaveCarryForwardToNextYear.cls
/* Batch Class to carry forward leave balance to next year */

global class LM_LeaveCarryForwardToNextYear implements Database.Batchable<sObject>
{
               global  String ContactList;
      
   
   global Database.QueryLocator start(Database.BatchableContext BC){
       system.debug('...........enter into loop');
      ContactList='Select id,name, Total_Leave__c from User where Date_of_Joining__c != null AND IsActive= true';
      // ContactList='Select id,name, Total_Leave__c from User where userrole.name=\' Developer\' AND Exit_Date__C= NULL';
                  return Database.getQueryLocator(ContactList);
              }

   global void execute(Database.BatchableContext BC, List<sObject> Scope){
                  
                 List<User> contactsToUpdate = new List<User>();
                  LM_CustomSetting__c currentYear = [Select Frequncy_Of_Run__c,No_Of_Annual_Leaves__c,No_of_leaves_to_be_carry_forward__c from LM_CustomSetting__c where Active__c = true limit 1];
                 for(sObject sobjects : scope){
                    
                              User SelectedContactList =(User)sobjects;
                              if(SelectedContactList.Total_Leave__c>=currentYear.No_of_leaves_to_be_carry_forward__c){
                              
                              SelectedContactList.Total_Leave__c=currentYear.No_of_leaves_to_be_carry_forward__c;
                              contactsToUpdate.add(SelectedContactList);
                               }
                      }
                       
                       
                   update contactsToUpdate;
            }
            
     global void finish(Database.BatchableContext BC){
               
               
           }
}