src/objects/LM_CustomSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Frequency_Text__c</fullName>
        <label>Frequency of run</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequncy_Of_Run__c</fullName>
        <label>Frequency of Credits</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Annual_Leaves__c</fullName>
        <label>Total Number Of Leaves/Year</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_leaves_to_be_carry_forward__c</fullName>
        <label>No. of leaves to be carry forward</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Leave Related Custom Settings</label>
</CustomObject>

src/classes/LM_CustomSetting_TestClass.cls
@isTest
private  class  LM_CustomSetting_TestClass
{
    static testMethod void CustomSetting()
        
    {
        LM_CustomSetting__c l1 = new LM_CustomSetting__c(name='testleave', Frequncy_Of_Run__c = '1;4;7;10',Frequency_Text__c='123', No_Of_Annual_Leaves__c=2,No_of_leaves_to_be_carry_forward__c=4 ,Active__c=True,Year__c='1190');
        insert l1 ;
        
        pagereference pr=new pagereference('/apex/LM_CustomSetting');
        Test.setCurrentPageReference(pr);
        Apexpages.StandardController sc = new Apexpages.standardController(l1);
        
        
        
        LM_CustomSetting  LeaveAllocation = new LM_CustomSetting(sc);
        LeaveAllocation.getFrequecny();
        LeaveAllocation.add();
        LeaveAllocation.customEdit();
        LeaveAllocation.currentRecord();
        LeaveAllocation.previousRecord();
        LeaveAllocation.Cancel();
        LeaveAllocation.save();
    }
}