src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_PaymentPageController.cls
public class PM_PaymentPageController 
{
    private final Payment__c paymentRecord;
    public Boolean chequeDetails{get;set;}
    public Boolean cashDetails{get;set;}
    public Boolean bankTransferDetails{get;set;}
    public PM_PaymentPageController(ApexPages.StandardController controller) 
    {
        this.paymentRecord=(Payment__c)controller.getRecord();
    }
    public PageReference dispSection()
    {
        
        if(paymentRecord.Payment_Mode__c == 'Cheque')
        {
            chequeDetails=true;
            cashDetails=false;
            bankTransferDetails=false;
        }
        else if(paymentRecord.Payment_Mode__c == 'Cash')
        {
            chequeDetails=false;
            bankTransferDetails=false;
            cashDetails=true;
        }
        else if(paymentRecord.Payment_Mode__c == 'Bank Transfer')
        {
            chequeDetails=false;
            cashDetails=false;
            bankTransferDetails=true;
        }
        else 
        {
            chequeDetails=false;
            cashDetails=false;
            bankTransferDetails=false;
        }
        return null;
    }
    
    
}