src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>App Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call/Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Workflow/Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estimation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing/QA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_Put_in_by_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Effort Put in by User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time worked in hours</description>
        <label>Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Complexity__c</fullName>
        <label>Task Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>V Simple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complex</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PM_BasicTimeEntryController.cls
public class PM_BasicTimeEntryController 
{
    String soqlvar = '';
    
    Time_Entry__c newTimeEntryInstance{get;set;}
    public Boolean RecentTimeEntryBlock{get;set;}
    
    
    public PM_BasicTimeEntryController () {
        soqlVar = 'select Project__r.Name,Related_Task__r.Name,Activity_Type__c,Activity_Description__c,Date__c,Effort__c,Effort_Put_in_by_User__r.Name,Task_Complexity__c,Client_Recoverable__c from Time_Entry__c where Effort_Put_in_by_User__c=  \'' + UserInfo.getUserId() + '\' order by Date__c desc';
        
        //TimeSheetUserId = ApexPages.currentPage().getParameters().get('id');
            //conName = new Contact();
            //conName = [Select id, Name from Contact where id=:TimeSheetUserId];
            //timeEntryRecordsDummy = new List<Time_Entry__c>();
            //dateInDateFormate = date.today();
    }
    
    
    
    
    public Time_Entry__c getNewInstance() 
    {
        newTimeEntryInstance = new Time_Entry__c ();
        return newTimeEntryInstance;
    }
    public PageReference saveStandardTimeEntry() 
    {
        if(newTimeEntryInstance.Project__c==null||newTimeEntryInstance.Related_Task__c==null||newTimeEntryInstance.Date__c == null||newTimeEntryInstance.Effort__c==null||newTimeEntryInstance.Effort__c==0.0)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Project, Related Task, Effort and Date are mandatory fields. Please fill those to Save a Time Entry Record');
            ApexPages.addMessage(myMsg);
        }
        else
        {
            newTimeEntryInstance.Effort_Put_in_by_User__c = UserInfo.getUserId();
            insert newTimeEntryInstance;
            RecentTimeEntryBlock = true;
        }
        con = null;
        ApexPages.Message myMsg=new ApexPages.Message(ApexPages.Severity.Confirm, 'Your Record Has Been Saved');
        ApexPages.addMessage(myMsg);
        return null;
    }
    public List<Time_Entry__c> getRecentItems() 
    {
        List<Time_Entry__c> listOfRecentTimeEntries = new List<Time_Entry__c>();
        soqlVar = 'select Project__r.Name,Related_Task__r.Name,Activity_Type__c,Activity_Description__c,Date__c,Effort__c,Effort_Put_in_by_User__r.Name,Task_Complexity__c,Client_Recoverable__c from Time_Entry__c where Effort_Put_in_by_User__c=  \'' + UserInfo.getUserId() + '\' order by Date__c desc';
        listOfRecentTimeEntries = (List<Time_Entry__c>)con.getRecords();
        return listOfRecentTimeEntries ;
    }
    public ApexPages.StandardSetController con 
    {
        get 
        {
            if(con == null) 
            {
                //system.assertEquals(soqlvar, null);
                con = new ApexPages.StandardSetController(Database.getQueryLocator(soqlvar));
                // sets the number of records in each page set
                con.setPageSize(5);
            }
            return con;
        }
        set;
    }
    public Boolean hasNext 
    {
        get 
        {
            return con.getHasNext();
        }
        set;
    }
 
    // indicates whether there are more records before the current page set.
   public Boolean hasPrevious 
    {
        get 
        {
        if(con!=null)
            return con.getHasPrevious();
        else return false;
        }
        set;
    }
 
    // returns the page number of the current page set
    public Integer pageNumber 
    {
        get 
        {
            return con.getPageNumber();
        }
        set;
    }
 
    // returns the first page of records
    public void first() 
    {
        con.first();
    }
 
    // returns the last page of records
    public void last() 
    {
        con.last();
    }
 
    // returns the previous page of records
    public void previous() 
    {
        con.previous();
    }
 
    // returns the next page of records
    public void next() 
    {
        con.next();
    }

    
    
}