src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval/Rejection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_Put_in_by_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Effort Put in by User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time worked in hours</description>
        <label>Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <label>Reports to Manager</label>
        <relationshipName>ProjectLead1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PM_TimeEntryApprovalController.cls
public class PM_TimeEntryApprovalController {

     /*public PageReference save()
     {
     upsert listOfTimeEntry;
     return null;
     }*/
    
    public String listOfProject{get;set;}
    public String projName{get;set;}
    public Boolean listEmpty{get;set;}
    public Boolean renderSection2{get;set;}
    public List<InnerWrapper> wrapperlist=new List<InnerWrapper>(); 
        
    public List<InnerWrapper> submittedWrapperList=new List<InnerWrapper>();
    public List<Time_Entry__c> listofSubmittedTimeEntries = new List<Time_Entry__c>();
    public List<Time_Entry__c> listOfTimeEntry = new List<Time_Entry__c>();
    
    public PM_TimeEntryApprovalController() {
        listEmpty=true;
    }


    

    //public List<Project__c> listofProjects = new List<Project__c>();
    public OuterWrapper newInstance;
    public class InnerWrapper
    {
        public Time_Entry__c instance{get;set;}
        public Boolean isChecked {get;set;}
        public InnerWrapper(Time_Entry__c t){
            instance = t;
            isChecked = true;
        }
    }
    
    public class OuterWrapper
    {
        public String projInstance{get;set;}
        public List<InnerWrapper> InnerWrapperList{get;set;}
    }
    public List<OuterWrapper> OuterWrapperlist;
    
    InnerWrapper wrapperInstance;
    
    public List<OuterWrapper> getProjectName()
    {
        OuterWrapperlist=new List<OuterWrapper>();
        String checkProjectName='';
        listOfTimeEntry=[select Project__c,Project__r.Name,Related_Task__c,Date__c,Activity_Description__c,Effort__c,Client_Recoverable__c,Effort_Put_in_by_User__c from Time_Entry__c where Status__c='Submitted' AND (Project__r.Project_Lead__c=:UserInfo.getUserId() OR  Project__r.Project_Lead__r.Project_Lead__c=:UserInfo.getUserId()) order by Project__c,Date__c];
        List<InnerWrapper> tempInnerWrapperList = new List<InnerWrapper>();
        for(Time_Entry__c timeEntry:listOfTimeEntry)
        {
            if(timeEntry.Effort_Put_in_by_User__c!=UserInfo.getUserId())
            {
                System.debug(timeEntry.Project__r.Name+' loooooooooooooooooooooooooooooooooooooooooooooooooooooook');
                if(checkProjectName == timeEntry.Project__r.Name)
                {    
                     wrapperInstance=new InnerWrapper(timeEntry);
                    tempInnerWrapperList.add(wrapperInstance);
                    checkProjectName= timeEntry.Project__r.Name;
                }
                else
                {
                    if(checkProjectName == '')
                    {
                        //OuterWrapperlist.add(newInstance);
                        wrapperInstance=new InnerWrapper(timeEntry);
                        tempInnerWrapperList.add(wrapperInstance);
                        checkProjectName = timeEntry.Project__r.Name;
                    }
                    else{
                        newInstance = new OuterWrapper();
                        newInstance.projInstance = checkProjectName ;
                        newInstance.InnerWrapperList = tempInnerWrapperList;
                        OuterWrapperlist.add(newInstance);
                        //system.assertEquals(OuterWrapperlist,null);
                        checkProjectName=timeEntry.Project__r.Name;
                        tempInnerWrapperList = new List<InnerWrapper>();
                        wrapperInstance=new InnerWrapper(timeEntry);
                        tempInnerWrapperList.add(wrapperInstance);
                        //checkProjectName = timeEntry.Project__r.Name;
                    }
                }
            }
          
          
        }
        //last outer wrapper instance
        newInstance = new OuterWrapper();
        newInstance.projInstance = checkProjectName ;
        newInstance.InnerWrapperList = tempInnerWrapperList;
        OuterWrapperlist.add(newInstance);
        if(OuterWrapperlist.size()==0)
        {
            listEmpty=false;
        }
        //system.assertEquals(OuterWrapperlist,null);
        return OuterWrapperlist;
    }
    
    
    
    public PageReference approve()
    {
        projName=Apexpages.currentPage().getParameters().get('projName');
        listofSubmittedTimeEntries = new List<Time_Entry__c>();
        for(OuterWrapper iterator:OuterWrapperlist)
        {
            
            if(iterator.projInstance==projName)
            {
                submittedWrapperList=iterator.InnerWrapperList;
                break;
            }
        }

        for(InnerWrapper iterator:submittedWrapperList)
        {

            if(iterator.IsChecked==true)
            {
                listofSubmittedTimeEntries.add(iterator.instance);
            }
        } System.debug(listofSubmittedTimeEntries+' eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee ');        
        for(Time_Entry__c iterator:listofSubmittedTimeEntries)
        {
            //System.debug('in');
            iterator.Status__c = 'Approved';
            iterator.Approval_Date__c = Date.today();
        }
        database.update(listofSubmittedTimeEntries);
        
        OuterWrapperList.clear();
        submittedWrapperList.clear();
        newInstance=null;
                 //System.debug(listofSubmittedTimeEntries);
                 //System.debug(submittedWrapperList);
        
        //renderSection2=true;
        return null;
    }
      public PageReference reject()
    {
        projName=Apexpages.currentPage().getParameters().get('projName');
        listofSubmittedTimeEntries = new List<Time_Entry__c>();
        for(OuterWrapper iterator:OuterWrapperlist)
        {
            
            if(iterator.projInstance==projName)
            {
                submittedWrapperList=iterator.InnerWrapperList;
                break;
            }
        }
        
        for(InnerWrapper iterator:submittedWrapperList)
        {

            if(iterator.IsChecked==true)
            {
                listofSubmittedTimeEntries.add(iterator.instance);
            }
        }System.debug(listofSubmittedTimeEntries+' ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo');     
        for(Time_Entry__c iterator:listofSubmittedTimeEntries)
        {
            iterator.Status__c = 'Rejected';
            iterator.Approval_Date__c = Date.today();
           
        }
        database.update(listofSubmittedTimeEntries); 
        
        OuterWrapperList.clear();
        submittedWrapperList.clear();
        newInstance=null;
        return null;
    }
   public List<InnerWrapper> getsubmittedRows()
    {
        return submittedWrapperList;
    }


}