src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Recoverable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client Recoverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_Put_in_by_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Effort Put in by User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time worked in hours</description>
        <label>Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TS-{DD}-{MM}-{YY}-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WeeklyViewController.cls
public class WeeklyViewController 
{

     public String dateInStringFormat{get;set;}
    
    
    List<dayHourWrapper> wrapList;
    public Date startOfWeek{get;set;}
    public Date Mondate{get;set;}
    public Date TueDate{get;set;}
    public Date WedDate{get;set;}
    public Date ThuDate{get;set;}
    public Date FriDate{get;set;}
    public Date SatDate{get;set;}
    public List<Date> days{get;set;} 
    public Boolean isVisible{get;set;}
    public PageReference assignDate() 
    {
        if(dateInStringFormat!=''&&dateInStringFormat!=null)
        {
            System.debug('Blank Date '+dateInStringFormat);
            enteredDate = date.parse(dateInStringFormat);
            startOfWeek = enteredDate.toStartOfweek();
            Date endOfWeek = enteredDate.toStartOfweek().addDays(6);
            Mondate = startOfWeek+1;
            TueDate = startOfWeek+2;
            WedDate = startOfWeek+3;
            ThuDate = startOfWeek+4;
            FriDate = startOfWeek+5;
            SatDate = startOfWeek+6;
            List<Time_Entry__c> listOfTimeEntries = [select Id,Date__c,Effort__c,Activity_Description__c,Client_Recoverable__c,Effort_Put_in_By_User__c,Effort_Put_in_By_User__r.Name,Project__c,Related_Task__c,Related_Task__r.Name,Project__r.Name from Time_Entry__c where Effort_Put_in_By_User__c=:UserInfo.getUserId() AND Date__c>=:startOfWeek AND Date__c<=:endOfWeek order by Project__r.Name asc];
            //System.debug(listOfTimeEntries );
            String tempProj = '';  
            dayHourWrapper wrapInstance;  
            wrapList =  new List<dayHourWrapper>();  
            for(Time_Entry__c instance:listOfTimeEntries)
            {
                if(tempProj==''||instance.Project__r.Name!=tempProj)
                {
                    if(tempProj!=null)
                        {
                            wrapList.add(wrapInstance);
                        }
                        tempProj = instance.Project__r.Name;
                        wrapInstance=new dayHourWrapper();
                        wrapInstance.sundayEffort=0;
                        wrapInstance.mondayEffort=0;
                        wrapInstance.tuesdayEffort=0;
                        wrapInstance.wednesdayEffort=0;
                        wrapInstance.thursdayEffort=0;
                        wrapInstance.fridayEffort=0;
                        wrapInstance.saturdayEffort=0;
                        wrapInstance.ProjectName = tempProj;
                        if(startOfWeek.daysBetween(instance.Date__c)==0)
                        {
                            wrapInstance.sundayEffort=wrapInstance.sundayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==1)
                        {
                            wrapInstance.mondayEffort=wrapInstance.mondayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==2)
                        {
                            wrapInstance.tuesdayEffort=wrapInstance.tuesdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==3)
                        {
                            wrapInstance.wednesdayEffort=wrapInstance.wednesdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==4)
                        {
                            wrapInstance.thursdayEffort=wrapInstance.thursdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==5)
                        {
                            wrapInstance.fridayEffort=wrapInstance.fridayEffort+instance.Effort__c;
                        }
                        else
                        {
                            wrapInstance.saturdayEffort=wrapInstance.saturdayEffort+instance.Effort__c;
                        }
                    }
                    else
                    {
                        if(startOfWeek.daysBetween(instance.Date__c)==0)
                        {
                            wrapInstance.sundayEffort=wrapInstance.sundayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==1)
                        {
                            wrapInstance.mondayEffort=wrapInstance.mondayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==2)
                        {
                            wrapInstance.tuesdayEffort=wrapInstance.tuesdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==3)
                        {
                            wrapInstance.wednesdayEffort=wrapInstance.wednesdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==4)
                        {
                            wrapInstance.thursdayEffort=wrapInstance.thursdayEffort+instance.Effort__c;
                        }
                        else if(startOfWeek.daysBetween(instance.Date__c)==5)
                        {
                            wrapInstance.fridayEffort=wrapInstance.fridayEffort+instance.Effort__c;
                        }
                        else
                        {
                            wrapInstance.saturdayEffort=wrapInstance.saturdayEffort+instance.Effort__c;
                        }
                    }
                    
                }
                wrapList.add(wrapInstance);
                System.debug(wrapInstance);
            }
            return null;
        }
    public class dayHourWrapper
    {
        public Decimal sundayEffort{get;set;}
        public Decimal mondayEffort{get;set;}
        public Decimal tuesdayEffort{get;set;}
        public Decimal wednesdayEffort{get;set;}
        public Decimal thursdayEffort{get;set;}
        public Decimal fridayEffort{get;set;}
        public Decimal saturdayEffort{get;set;}
        public String ProjectName{get;set;}
        
    }   
    
    
    public String timeEntryTab{get;set;}
    public String WeeklyViewTab{get;set;}
    public String BasicWizardTab{get;set;}
    public String Home{get;set;}
    Date enteredDate;
    public WeeklyViewController()
    {
        timeEntryTab='#';
        WeeklyViewTab='active';
        dateInStringFormat='';
        BasicWizardTab='#';
        Home='#';
    }
    public List<dayHourWrapper> getAllEntries()
    {
        return wrapList;
    }
    
}