src/objects/Sales_Order__c.object
<CustomObject>
    <description>Letter Of Engagement.</description>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <label>Billing Type</label>
        <picklist>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Proposed End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Date__c</fullName>
        <label>Actual Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Milestone_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Milestone Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Type__c</fullName>
        <formula>TEXT( Sales_Order__r.Billing_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_Reference_Number__c</fullName>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Milestone Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Milestone_Revenue__c</fullName>
        <label>Planned Milestone Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completely Invoiced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Rate__c</fullName>
        <label>Unit Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <label>Sales Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PM_CreateSalesOrderItems.cls
global class PM_CreateSalesOrderItems {
    /* 
To Create the salesorder items for the fixed price salesorder 

Author:Ashwin Extentor 

Created date : 13/02/2013

Modification date :29/03/2013

Reason :To copy the currency type from parent salesorder to child salesorder items 



*/
    public Boolean refreshPage{get;set;}
    public Boolean WholePage{get;set;}
    public String selectedValue{get;set;}
    Public Sales_Order_Item__c SelectedSalesOrderItems; 
    Public List<Sales_Order_Item__c> FetchSalesOrderItems{get;set;}
    
    Public Sales_Order__c  SelectedSalesOrder {get;set;}
    id salesOrderId ;
    Public PM_CreateSalesOrderItems(ApexPages.StandardController controller)
    {
        salesOrderId=ApexPages.currentPage().getParameters().get('id');
        SelectedSalesOrder=[Select name,id ,CurrencyIsoCode from Sales_Order__c where id=:salesOrderId AND RecordType.name='Service Type' AND Billing_Type__c='FP'];
        
        resetQueries();
    }
    
    public void resetQueries()
    {
        
        
        FetchSalesOrderItems=[Select Name,Actual_Date__c,Actual_Milestone_Revenue__c,Milestone_Reference_Number__c,Planned_Date__c,Planned_Milestone_Revenue__c,Sales_Order__c,Status__c,Unit_Rate__c  from Sales_Order_Item__c where Sales_Order__c =:salesOrderId]; 
        
    }
    
    public Sales_Order_Item__c  getSalesOrderitems(){
        SelectedSalesOrderItems = new Sales_Order_Item__c();
        //SelectedSalesOrderItems =[Select Assigned_User__c,Role__c,Sales_Order__c,Start_Date__c, Location__c,Percentage__c,End_Date__c from Sales_Order_Item__c where Sales_Order__c =:SelectedSalesOrder.id ];
        return SelectedSalesOrderItems;
    } 
    
    
    public pageReference Add()
    {
        try{
            
            SelectedSalesOrderItems.Sales_Order__c=salesOrderId;
            
            SelectedSalesOrderItems.CurrencyIsoCode= SelectedSalesOrder.CurrencyIsoCode;
            //SelectedSalesOrderItems.Planned_Date__c=Date.Today();
            //SelectedSalesOrderItems.Actual_Date__c=Date.Today();
            database.insert(SelectedSalesOrderItems);
            SelectedSalesOrderItems = new Sales_Order_Item__c();
            
            resetQueries();
            
        }
        catch (Exception ex) {
            ApexPages.addMessages(ex);
            system.debug(ex);
            
        }
        return null;
    }
    
    
    
    public PageReference QuickSave() 
    {
        update FetchSalesOrderItems ;
        
        return null;
    }
    
    
    
    public PageReference remove() 
    {
        //system.assertEquals('in','here');
        selectedValue=ApexPages.currentPage().getParameters().get('removeRow');
        
        Sales_Order_Item__c DeleteSalesOrderItems=new Sales_Order_Item__c(Id=selectedValue);
        delete DeleteSalesOrderItems ;
        resetQueries();
        return null;
        
    }
}